### ISSUE TITLE
Example for form binding

### ISSUE THREAD

**Issue by litti** [feathers-plus/feathers-vuex#101]
I want to bind the values I get from feathers-vuex to a form. Therefore I want to use the v-model directive. According to https://vuex.vuejs.org/en/forms.html I'm wondering if there's already a way to use a computed two-way property with feathers-vuex.

For now I'm doing it like

````
<template>
  <div>
    <h4>objecttype details</h4>
    <p>Please enter the details of the object type below.</p>
      <input v-model="item.name" float-label="name" />
    <q-btn label="save" @click="save" />
  </div>
</template>

<script>

  import {
    mapGetters,
    mapState,
    mapActions
  } from 'vuex'

  export default {
    components: {LanguageInput},
    props: ['isNew', 'id'],
    data() {
      return {
      }
    },
    computed: {
      ...mapGetters('objecttype', {
        getItemFromStore: 'get'
      }),
      ...mapState(['objecttype']),
      item() {
        return this.objecttype.keyedById[this.objecttype.currentId];
      }
    },
    methods: {
      save() {
        //console.log(this.dataitem);

        this.updateItemInApi([this.objecttype.currentId, this.objecttype.keyedById[this.objecttype.currentId], {}]);

      },
      ...mapActions('objecttype', {
        getItemFromApi: 'get',
        createItemInApi: 'create',
        updateItemInApi: 'update'
      })
    },
    created() {
      this.getItemFromApi(this.id);
    }
  }

</script>
````

not knowing if it's the right way to do it :-) Maybe there is a better example for form-binding?

**Comment by marshallswain** [comment]
I have a nice update in the works that simplifies usage with forms.  I've been testing it out for a couple of weeks, and it works well.  I'll publish it within the next couple of weeks.  No breaking changes but lots of great new features!

**Comment by marshallswain** [comment]
This solution has been out for a while!  I've finally added an example to the docs.  Check out the common patterns page.
