### ISSUE TITLE
async socket uri

### ISSUE THREAD

**Issue by Sparki2002** [feathers-plus/feathers-vuex#105]
Hi,

I need a little help:
How can I asynchronous add the socket transport to the feathers client?

I need to get the socket uri from an rest endpoint, but I want to load my page (with working vuex store) on the same time

**Comment by marshallswain** [comment]
You could actually just wrap it in a function, like what @Mattchewone shows in one of his latest articles: https://medium.com/@mattchewone/feathersjs-nuxt-ssr-authentication-75e97b6ce125

**Comment by marshallswain** [comment]
I'm going to close this, since it couldn't be handled at the `feathers-vuex` level, anyway.  The solution given should work properly.
