### ISSUE TITLE
initAuth is not populating auth.user in feathers 3.0

### ISSUE THREAD

**Issue by guzz** [feathers-plus/feathers-vuex#106]
I was having a problem with initAuth that after the first login if the page was refreshed the user would not be populated, yet the payload was there.

I created a fix in a fork that i´ll post below to help anyone with the same problem.

I changed the initAuth function in /src/utils.js

```
var initAuth = exports.initAuth = function initAuth(options) {
  var _Object$assign = Object.assign({}, authDefaults, options),
      commit = _Object$assign.commit,
      dispatch = _Object$assign.dispatch,
      req = _Object$assign.req,
      moduleName = _Object$assign.moduleName,
      cookieName = _Object$assign.cookieName;

  if (typeof commit !== 'function') {
    throw new Error('You must pass the `commit` function in the `initAuth` function options.');
  }
  if (!req) {
    throw new Error('You must pass the `req` object in the `initAuth` function options.');
  }

  var accessToken = readCookie(req.headers.cookie, cookieName);
  var payload = getValidPayloadFromToken(accessToken);

  if (payload) {
    commit(moduleName + '/setAccessToken', accessToken);
    commit(moduleName + '/setPayload', payload);
  }
  try {
    var user = dispatch(moduleName + '/populateUser', payload.userId)
    return Promise.resolve(user);
  } catch (error) {
    return Promise.resolve(undefined);
  }
};
```

Hope it helps someone.

**Comment by marshallswain** [comment]
It's always appreciated when people publish solutions to the community.  Thank you!  They may also benefit from this article by @Mattchewone: https://medium.com/@mattchewone/feathersjs-nuxt-ssr-authentication-75e97b6ce125

They may even benefit from this comment: https://github.com/feathers-plus/feathers-vuex/issues/93#issuecomment-376476715

**Comment by jscottsf** [comment]
Not 100% sure about the solution @guzz. The populateUser would fail since the featherClient authenticate hasn't been called yet with the JWT access token. Following the Medium solution, the auth happens AFTER the initAuth call.

**Comment by jscottsf** [comment]
Not yet. Starting a new UI project soon so will be trying it soon.

**Comment by guzz** [comment]
Hi @NickBolles for me it´s working fine, I guess it was just the version I was using back them but I´m using for a while and having no problems.

**Comment by NickBolles** [comment]
@guzz sweet. Can we close this then?

**Comment by guzz** [comment]
Yes, it´s fine.

Should I close it or you prefer to keep track of issues yourself?

**Comment by NickBolles** [comment]
@guzz I don't have access to close it, so you will have to.
