### ISSUE TITLE
Setting paginate to false does not work with find getter

### ISSUE THREAD

**Issue by dkrotts** [feathers-plus/feathers-vuex#108]
### Steps to reproduce

Use service getters to find a value and set params.paginate to false:

`const res = store.getters['myService/find']({
  paginate: false 
})`

### Expected behavior

`res` should be an Array

`console.log(res) // [ ... ]`

### Actual behavior

`res` will always be a pagination object:

`console.log(res)
//  {
    total: n,
    limit: n,
    skip: n,
    data: [ ... ]
}`

**Module versions** (especially the part that's not working):

feathers-vuex 1.1.4

**Comment by dkrotts** [comment]
Upon closer inspection, it seems the docs contradict themselves on this:

> ### Service Getters
> - `find(params) {Function}` - a helper function that allows you to use the [Feathers Adapter Common API](https://docs.feathersjs.com/api/databases/common.html) and [Query API](https://docs.feathersjs.com/api/databases/querying.html) to pull data from the store.  This allows you to treat the store just like a local Feathers database adapter (but without hooks).
>   - `params {Object}` - an object with a `query` object and an optional `paginate` boolean property. The `query` is in the FeathersJS query format.  **You can set `params.paginate` to `false` to disable pagination for a single request**.

and later on...

> ### The `find` getter
> 
> The `find` getter queries data from the local store using the same Feathers query syntax as on the server.  It is synchronous and returns the results of the query with pagination.  **Pagination cannot be disabled.**  It accepts a params object with a `query` attribute.  It does not use any other special attributes.  The returned object looks just like a paginated result that you would receive from the server:

**Comment by marshallswain** [comment]
@dkrotts Ah, yes.  The docs definitely require updating.  

The current behavior is the expected behavior, but the docs need to be updated.  I've just gotten sick of writing guards in my code for when a service has pagination enabled or disabled, or changes between them.  So, getters always return the data at `data`.  Feathers will do the same thing in a future release.

**Comment by HarisHashim** [comment]
I got stung by this! So there is no way to change paginate to true or false for each query?

Btw I did this in index.js in store folder and it looks like pagination is not disabled too! 


```
  plugins: [
    service("stats", {
      paginate: false
    }),
```

Did I do anything wrong or this part of documentation is also wrong?

```
**Service State**
Each service comes loaded with the following default state:
<... snip>
paginate {Boolean} - Indicates if the service has pagination turned on. This changes the response of the find action and getter to match the response that Feathers gives.
```

**Comment by marshallswain** [comment]
@HarisHashim Thanks for pointing out that line.  It was definitely inaccurate.  Pagination is always controlled from the server.  I'm not sure where my brain was when I wrote that line.

**Comment by marshallswain** [comment]
I was confused when I wrote the original docs for this and haven't had the need to go back and fix it, yet.  Pagination is controlled by the service, whether on the client as a client-only service (like feathers-memory) or on the server like most services.  The find getter, itself, does not paginate data, nor should it.  If anybody would like to make a PR to the docs, I'll review it.

@laurensiusadi if you want to tell me what it is you are trying to accomplish, I might have another suggestion.

**Comment by laurensiusadi** [comment]
@marshallswain 
My problem is, I have 25 entry on database, but only see 10 on vuex store.
I want to see all entry, whether it's 25 or 1000, on my vuex store.

**Comment by laurensiusadi** [comment]
@marshallswain 
Found my problem, this has nothing to do with client side.
I use feathers cli to generate my services on the server side.
```
module.exports = function (app) {
  const Model = createModel(app)
  const paginate = app.get('paginate') <---

  const options = {
    Model,
    paginate <---
  }

  // Initialize our service with any options it requires
  app.use('/tasks', createService(options))

  // Get our initialized service so that we can register hooks
  const service = app.service('tasks')

  service.hooks(hooks)
}
```
Just need to remove those `paginate`

**Comment by marshallswain** [comment]
Setting params.paginate to false has a new function in Feathers-vuex@2.x.  Server-side pagination is now fully supported on the client with the `makeFindMixin`.  paginated queries aren't reactive, though.  You can set `paginate: false` to restore the previous behavior and get reactive lists again.  Thanks for the update @laurensiusadi.
