### ISSUE TITLE
Different find requests made to the same service

### ISSUE THREAD

**Issue by joshsavage** [feathers-plus/feathers-vuex#113]
I'm making a dashboard which contains multiple components each needing to pull different data from the same service. The first find action works fine however when the next component makes a requests the list contains it's query results appended to the last queries results in the store. I had thought I'd be able to use the qid to identify requests but this doesn't seem to work. 

What is the best way to identify different requests on the same service? 

Example code...

Dashboard Component 

```
export default {
  name: 'Dashboard',
  components: {
      LineChart
  }, 
  methods: {
    ...mapActions('dashboard-data', {
      findDashboardData: 'find'
    })
  },
  computed: {
    ...mapGetters('dashboard-data', {
      dashboardData: 'list'
    })
  },
  async created () {
     let startOfLastWeek = moment().subtract(1, 'week').startOf('isoWeek')
     let endOfThisWeek = moment().endOf('isoWeek')
    
     await this.findDashboardOverviewList({
      query: {
        report_date: { $gte: startOfLastWeek.format(), $lte: endOfThisWeek.format() },
        groupby: 'week',
        '$sort': { '_id': -1 } 
      },
      qid: 'main'
    })
  }
}
```

Linechart Component (inside of dashboard)

```
export default {
  name: 'LineChart',
  methods: {
    ...mapActions('dashboard-data', {
      findLineChartData: 'find'
    })
  },
  computed: {
    ...mapGetters('dashboard-data', {
      lineChartData: 'list'
    })
  },
  async created () {
     let startDate = moment().subtract(1, 'month')
     let endDate = moment().endOf('isoWeek')
    
     await this.findLineChartData({
      query: {
        report_date: { $gte: startOfLastWeek.format(), $lte: endOfThisWeek.format() },
      },
      qid: 'linechart'
    })

    console.log(JSON.stringify(this.lineChartData)) // <-- Displays dashboardData at the start
  }
}
```
The final console.log displays the dashboard data at the start with lineChartData appended afterwards with no way to distinguish.

**Comment by marshallswain** [comment]
@joshsavage the `list` getter always returns an array of all data in the `dashboard-data` store.  You'll need to use the `find` getter with the same query as the `find` action to separate the data.  Another option would be to install the latest pre-release and use the response from the actions, directly.  You can read more about the coming release, here: https://github.com/feathers-plus/feathers-vuex/blob/models/notes.md#actions-return-reactive-store-records

I highly recommend upgrading, now.  There are no breaking changes.

`npm i feathers-vuex@pre --save`

**Comment by marshallswain** [comment]
@joshsavage did my answer make sense to solve your problem?

**Comment by marshallswain** [comment]
@joshsavage thanks for the update
