### ISSUE TITLE
TypeScript helpers suggestion.

### ISSUE THREAD

**Issue by nickmessing** [feathers-plus/feathers-vuex#114]
Hello,

I have used `feathers-vuex` with TypeScript in a project and I made a set of helpers that I think could be really useful to other developers, [here](https://gist.github.com/nickmessing/cb961d03f5dd851933057add13809794) you can see the source code and below is an example of usage:

```ts

import Vue from 'vue'
import { Component } from 'vue-property-decorator'
import { namespace, Action } from 'vuex-class'
import { ActionGet, ActionCreate, ActionPatch } from '../types/feathers'
import { Person } from '../types/models'

const PeopleAction = namespace('people', Action)

@Component
export default class CreateEditPeople extends Vue {
  @PeopleAction('get') getPerson: ActionGet<Person>
  @PeopleAction('create') createPerson: ActionCreate<Person>
  @PeopleAction('patch') patchPerson: ActionPatch<Person>
  // some extra here
}
```

TypeScript reads it really well and all suggestions and autocomplete helps a lot.

**Comment by marshallswain** [comment]
Cool!  

@nickmessing how would one use your `feathers-vuex-helpers.ts` file in their project?  This looks like something that ought to go into the docs in a "Using with TypeScript" section.  We can link to your helpers gist.

**Comment by nickmessing** [comment]
@marshallswain, I could finalize the typings and make a PR to make them universal so people can use them with bot [class-component definition](https://gist.github.com/nickmessing/f206056cb0eb8879b068f727a1aaecbb) and [classic component definition](https://gist.github.com/nickmessing/dfc8264ecc17d68ed5aaa82bd253d4e5) if you want to support that.

**Comment by marshallswain** [comment]
I know absolutely nothing about TypeScript, but I know that a lot of people
will appreciate this. I might even learn something, here, so I’d like to
support it, yeah. :) please make a PR when you have time. That would be
terrific!

**Comment by marshallswain** [comment]
@rayfoss is your 👎 reaction a reflection of your dislike for TypeScript?  Or is it about the quality of the recommendation?

**Comment by rayfoss** [comment]
@marshallswain Features should have a good reason to exist because they take time to add. My vote is just a reflection of this features being 99% unlikely to be of use to me. I'm waiting for native types to come to Node. Fun fact, I used to use Typescript in Angular 2. 

I think TS support is good for the project, as long as it doesn't get in the way for everybody else with a ton of irrelevant files and dependencies everywhere. Forcing it is definitely a bad idea, as there are many many hold outs and designers using js or flow.

**Comment by marshallswain** [comment]
@rayfoss Thanks for the update.  I have similar sentiment.  If @nickmessing's suggestions work without requiring modifying the repo, that's the perfect solution, in my opinion.

I've added a link to this issue in the docs.  I'm closing this issue, now.  Thanks, guys.

**Comment by marshallswain** [comment]
Docs link is here: https://feathers-plus.github.io/v1/feathers-vuex/common-patterns.html#Working-with-TypeScript

**Comment by NickBolles** [comment]
I have some typings for feathers-vuex too, I'm planning on putting together a PR at some point, but for now here they are. 

``` typescript

import feathers, { Application } from "@feathersjs/feathers";
import { StoreOptions, Plugin, Commit, Dispatch } from "vuex";
import { PluginObject } from "vue";
import { Request } from "request";
import { type } from "os";

/**
 * Vue Plugin
 */
export interface FeathersVuexModel<ModelType = any> {
  namespace: string;
  className: string;
  modelName: string;
  options: FeathersVuexOptions;
  new(data?: Partial<ModelType>, options?: FeathersVuexModelOptions)
  reset: () => Promise<FeathersVuexModel<ModelType>>
  clone: () => Promise<FeathersVuexModel<ModelType>>
  create: (params: Partial<ModelType>) => Promise<FeathersVuexModel<ModelType>>
  patch: (params: Partial<ModelType>) => Promise<FeathersVuexModel<ModelType>>
  remove: (params: Partial<ModelType>) => Promise<FeathersVuexModel<ModelType>>
  save: (params: Partial<ModelType>) => Promise<FeathersVuexModel<ModelType>>
  update: (params: Partial<ModelType>) => Promise<FeathersVuexModel<ModelType>>
}

interface FeathersVuexModelOptions {
  isClone?: boolean;
  skipCommit?: boolean;
}

export type FeathersVuexGlobalModelsIndex<T> = {
  [P in keyof T]: FeathersVuexModel<T[P]> | FeathersVuexGlobalModels;
}

// export interface FeathersVuexGlobalModelsByPath<T> {
//   byServicePath: {
//     [P in keyof T]: FeathersVuexModel<T[P]>;
//   };
// }

/**
 * @description The type for the $FeathersVuex vue plugin. To type this stronger include the
 * following in a typings.d.ts file
 *
 *
 * @example
 * declare module "vue/types/vue" {
 *   import { FeathersVuexGlobalModels } from "feathers-vuex";
 *   interface Vue {
 *     $FeathersVuex: FeathersVuexGlobalModels<Services>;
 *   }
 * }
 *
 * @description Where services is something like this
 * @example
 * interface Services {
 *   users: User
 *   //...
 * }
 *
 * interface User {
 *   name: string;
 *   rating: number;
 *   //...
 * }
 * @description
 * The second generic is for the "byServicePath" property, and can be used in a similar way, just make a
 * ServicesByPath interface, where the key for the service is the path, not the name
 *
 * @example
 * interface Services {
 *   usersPath: User
 *   //...
 * }
 *
 * declare module "vue/types/vue" {
 *   import { FeathersVuexGlobalModels } from "feathers-vuex";
 *   interface Vue {
 *     $FeathersVuex: FeathersVuexGlobalModels<Services, ServicesByPath>;
 *   }
 * }
 *
 */
type FeathersVuexGlobalModels<T = any, P = any> = FeathersVuexGlobalModelsIndex<T>;//& FeathersVuexGlobalModelsByPath<P>;

/**
 * Init Auth
 */
interface InitAuthOptions {
  commit: Commit;
  dispatch: Dispatch;
  req: Request;
  cookieName: string;
  moduleName: string;
}
export function initAuth(options: InitAuthOptions): Promise<object>;

/**
 * Auth module factory
 */
interface FeathersVuexAuthOptions<State = FeatheresVuexAuthState> extends FeathersVuexStoreOptions<State> {
  userService: string
}

interface FeatheresVuexAuthState<UserType = any> {
  accessToken?: string, // The JWT
  payload: Object, // The JWT payload

  isAuthenticatePending: boolean,
  isLogoutPending: boolean,

  errorOnAuthenticate: Error | undefined,
  errorOnLogout: Error | undefined,
  user: UserType
}

interface FeathersVuexServiceState<ModelType = any, IDType = string> extends FeathersVuexCoreProps {
  ids: IDType[],
  keyedById: {
    [i: string]: ModelType
  }, // A hash map, keyed by id of each item
  currentId?: IDType, // The id of the item marked as current
  copy?: ModelType, // A deep copy of the current item
  servicePath: string // The full service path
  paginate: boolean, // Indicates if pagination is enabled on the Feathers service.

  isFindPending: boolean,
  isGetPending: boolean,
  isCreatePending: boolean,
  isUpdatePending: boolean,
  isPatchPending: boolean,
  isRemovePending: boolean,

  errorOnfind: Error | undefined,
  errorOnGet: Error | undefined,
  errorOnCreate: Error | undefined,
  errorOnUpdate: Error | undefined,
  errorOnPatch: Error | undefined,
  errorOnRemove: Error | undefined
}


interface FeathersVuexCoreProps {
  /**
   * @default 'id'
   */
  idField: string;
  /**
   * @default false
   */
  autoRemove: boolean;
  /**
   * @default true
   */
  enableEvents: boolean;
  /**
   * @default false
   */
  addOnUpsert: boolean;
  /**
   * @default false
   */
  diffOnPatch: boolean;
  /**
   * @default false
   */
  skipRequestIfExists: boolean;
  /**
   * @default false
   */
  preferUpdate: boolean;
  /**
   * @default false
   */
  replaceItems: boolean;
}
interface FeathersVuexStoreOptions<Store> extends Pick<StoreOptions<Store>, 'state' | 'getters' | 'mutations' | 'actions'> { }

interface FeathersVuexOptions<Store = any> extends FeathersVuexStoreOptions<Store>, FeathersVuexCoreProps {

  /**
   * @default 'path'
   */
  nameStyle?: 'short' | 'path';
  namespace: string;
  apiPrefix: string
  modelName: string;
  instanceDefaults?: any;
  /**
   * @debug false
   */
  debug: boolean;
}

/**
 * default export
 */
interface FeathersVuexResult {
  service<ModelType = any, IDType = string>(servicePath: string, options?: Partial<FeathersVuexOptions>): Plugin<FeathersVuexServiceState<ModelType, IDType>>;
  auth<UserType>(options?: FeathersVuexAuthOptions): Plugin<FeatheresVuexAuthState<UserType>>;
  FeathersVuex: PluginObject<any>;
}

export default function (client: Application, options: Partial<FeathersVuexOptions>): FeathersVuexResult;

declare namespace FeathersVuex {
  export interface FeathersVuexPluginType extends FeathersVuexGlobalModels { }
}

declare module "vue/types/vue" {
  interface Vue {
    $FeathersVuex: any;
  }
}


```

**Comment by bartduisters** [comment]
@NickBolles I just removed my client side project that used TypeScript, just to regenerate it as a JavaScript project.

Steps I tried to add typings to feathers-vuex:
- Check if a @types/feathers-vuex definition exist, it does not.
- Add my own typings directory to 'typeRoots' in tsconfig, specify a directory with the name feathers-vuex, with in it a index.d.ts with your code in it.
- Renamed the 'declare module 'vue/types/vue' in your file to 'feathers-vuex' since that is what the cli told me to do (create a .d.ts file with a 'declare module "feathers-vuex";' in it. I then get an error that it can not be augmented. I delete all the code above 'declare module "vue/types/vue" in your file (which is "feathers-vuex" in my file). Then the error goes away. But it would still not recognize the typings.

Finally, I did what I said in the beginning and removed TypeScript just so I can follow along with a tutorial using this library.

**Comment by NickBolles** [comment]
@bartduisters There are probably other ways to achieve this without built in typings (which I believe are coming in v2), but here's how I have it setup

I have a folder `@types/feathers-vuex` with an `index.d.ts` in it with that content from my post above (which I just updated). Then I have a file `@types/feathers-vuex-app.d.ts` with the following content in it. 

```typescript
import { Services } from "../store";
import { FeathersVuexGlobalModels } from "feathers-vuex";

declare module "vue/types/vue" {
  interface FeathersVuexPluginType extends FeathersVuexGlobalModels<Services> { } 
}

```
This will extend the Vue prototype typings with 

This file is picked up by typescript by declaring it in the "typeRoots" in the tsconfig.json. 
```json
{
  "compilerOptions": {
    "typeRoots": [
      "./node_modules/@types/",
      "./client/@types/"
    ],
  }
}
```

where `store/index.ts` contains this (and more). You should probably break this into it's own file actually, but I have it in `store/index.ts` along with my store content. Also this is importing the user service from my feathers server, which was generated by feathers-plus cli. It could simply be an interface that you define though.

```typescript
import { User } from "../../server/services/v1/users/users.interface";
export interface Services {
  users: User;
}
```

**Comment by bartduisters** [comment]
Thanks for the clarification. Will try it as soon as I try another project with TypeScript and feathers-vuex!
