### ISSUE TITLE
instance.commit() with deep values

### ISSUE THREAD

**Issue by marshallswain** [feathers-plus/feathers-vuex#116]
When commit an clone back to the original instance, removing an item from an array, then commiting can result in the array not changing.  For example, if we remove a role from a user, then commit, the role will still be present because the array values are deep merged.

```js
const todo = new User({
  roles: ['admin']
})
const todoClone = todo.clone()

todoClone.roles = []
todoClone.commit()

console.log(todo.roles.join( , ')) // --> 'admin'
```

This is a bug.  We should probably be doing a shallow merge.

**Comment by jscottsf** [comment]
This seems to have a problem when removing array items. Will do more testing. The merge worked when I added or changed items. But removing items didn't sync correctly across clients.
