### ISSUE TITLE
`isFindPending` states per pagination object

### ISSUE THREAD

**Issue by Mattchewone** [feathers-plus/feathers-vuex#117]
### Feature?

I think it would be good to have `isFindPending` and other "loading" states within the pagination objects. 
This way you can load something in the default pagination, and when you load data into another pagination object, if you are using the `isFindPending` to show a loading state and the secondary pagination object loads data you will see `loading` state.

Would be nice to be able to show loading state on a per-pagination basis.

We could leave the default loading states top-level for `default` pagination object as to not break anything and also then include a per pagination object loading states.

Thoughts?

**Comment by marshallswain** [comment]
Good idea.  Yep!

**Comment by marshallswain** [comment]
I've implemented a similar feature as part of the `feathers-vuex-data` component in `feathers-vuex@1.7.0-pre.6`.  Each component now has its own pagination tracking that's kept in the service store.
