### ISSUE TITLE
Is it possible to access the feathersClient instance used by feathers-vuex directly?

### ISSUE THREAD

**Issue by mtbksouth** [feathers-plus/feathers-vuex#118]
I'm sorry if I'm asking in the wrong forum, and also apologize for any misconceptions I may have about vuex or feathers; I'm new to both. 

I'm trying to decide if this package is the right one for me and I have scoured the docs for an answer to the above question. I have a component which will use a handful of feathers services which maintain arrays with thousands of objects, but I don't need to listen on those services app-wide, just in that one component. Thus, I don't want to store the data in vuex, since it's available app-wide, and has the overhead of commits and such. 

Can I set a listener on the feathersClient instance directly from within one of my components, so that I'm only listening to a particular feathers service when that component is mounted, and such that the data sent by that service is not stored in vuex, but while still using the same feathersClient instance that feathers-vuex uses, so I can stay auth'd and such?

**Comment by gustojs** [comment]
Yes you can, just import feathersClient to the component of your choice.

**Comment by marshallswain** [comment]
@mtbksouth Yep!  @gustojs gave the right answer.  Use it like any module in Node.
