### ISSUE TITLE
Fails silently when idField misconfigured, `find` action returns array of `undefined`s

### ISSUE THREAD

**Issue by cameronblandford** [feathers-plus/feathers-vuex#121]
### Steps to reproduce

Set your idField to something that isn't your backend's `id` field, or alternatively, use mongodb as your database and leave out the `idField` parameter. Try to use the `find` action in the service module (with a corresponding feathers service as the endpoint, populated with data).

### Expected behavior

I would have liked some sort of error message saying that there was no id found, maybe with a hint that my idField might be misconfigured.

### Actual behavior

Spent a solid 4 hours trying to debug the issue, wondering why the websocket response was returning data but it disappeared inside my resolved promise (pagination/count metadata was present, and array of what should have been 10 returned objects showed up as an array of 10 `undefined`s). 

### Notes

I don't know if prompting the user to check their idField is the right answer, but it's certainly an opaque bug to get - any kind of insight into that having been the issue would have been incredibly helpful and saved me a headache.

PS: Obviously you guys are making something incredible here and I don't want any possible bad tones in this bug report to take away from that, feathers-vuex is a godsend. If I come off as cranky, it's just because it's 1:37am and I finally figured this out. Much love!

**Comment by marshallswain** [comment]
@cameronblandford Sorry you ran into this issue.  I failed to document turning on `debug` mode.  The code to warn you is already in place.  https://github.com/feathers-plus/feathers-vuex/blob/master/src/service-module/mutations.js#L14

I've updated the docs.

**Comment by cameronblandford** [comment]
Awesome, thank you! 👍
