### ISSUE TITLE
FeathersVuex plugin is undefined

### ISSUE THREAD

**Issue by HarisHashim** [feathers-plus/feathers-vuex#123]
Following documentation for [Vue Plugin API](https://feathers-plus.github.io/v1/feathers-vuex/vue-plugin.html). I am trying to use FeathersVuex plugin. By following code in the documentation.

My code is as follows

```
import Vue from "vue";
import Vuex from "vuex";
import feathersVuex from "feathers-vuex";
// import feathersClient from "../api/feathers-client";
import { feathersClient } from "../plugins/feathers";

import example from "./module-example";

Vue.use(Vuex);

const { service, auth, FeathersVuex } = feathersVuex(feathersClient, {
  idField: "_id"
});

console.log(
  "FeathersVuex: " + FeathersVuex + "  feathersClient: " + feathersClient
);

Vue.use(FeathersVuex);
```

I am getting bellow error
> vue.runtime.esm.js?ff9b:4746 Uncaught TypeError: Cannot read property 'install' of undefined
    at Function.Vue.use ...

The way I see it the error is consistent with my console.log that says FeathersVuex is undefined

> FeathersVuex: undefined  feathersClient: [object Object]

I was thinking that something is wrong with feathersClient but the console log looks OK. But here is my feathersClient code, in case that can help.

```
import feathers from "feathers";
import hooks from "feathers-hooks";
import socketio from "feathers-socketio";
import auth from "feathers-authentication-client";
import io from "socket.io-client";

const socket = io("http://localhost:3030", { transports: ["websocket"] });

const feathersClient = feathers()
  .configure(hooks())
  .configure(socketio(socket))
  .configure(auth({ storage: window.localStorage }));

export default ({ app, router, Vue }) => {
  Vue.prototype.$feathers = feathersClient;
};

export { feathersClient };
```

Appreciate help or additional documentation on how to troubleshoot FeathersVuex is undefined in bellow code

```
const { service, auth, FeathersVuex } = feathersVuex(feathersClient, {
  idField: "_id"
});
```

TIA
Haris

**Comment by marshallswain** [comment]
Which version do you have installed?

**Comment by HarisHashim** [comment]
@marshallswain "version": "1.1.4" , checked from package.json in node_modules\feathers-vuex folder

**Comment by marshallswain** [comment]
I have no idea why this would be the case.  I'm using this exact code in multiple projects.  Could you set a debugger in your inspector and see if you can tell what's going on?

```js
import Vue from "vue";
import Vuex from "vuex";
import feathersVuex from "feathers-vuex";

debugger
```

Even check the actual code in the node_modules folder to make sure it's exported.

**Comment by HarisHashim** [comment]
Thanks for your help. I try it again with debugging and it works. Must be some silly mistake on my part.
