### ISSUE TITLE
Issue with pagination object

### ISSUE THREAD

**Issue by Mattchewone** [feathers-plus/feathers-vuex#125]
I need to create a reproducible example but I wanted to make a note of the issue I am seeing.

When creating a computed property from the service's pagination object, when navigating to a page that has not had the `default` prop created within the `pagination` object, means this is not reactive as this is being merged.

The pagination object needs to be a new object so that Vue with ensure it's reactive.

**Comment by marshallswain** [comment]
Closed in `feathers-vuex@1.4.1` by #126.
