### ISSUE TITLE
Service relationships in find getter are not populated

### ISSUE THREAD

**Issue by plunkettscott** [feathers-plus/feathers-vuex#128]
### Steps to reproduce

1 ) 
Create a service, set the instanceDefaults to include a relationship with another service.

```js
const servicePlugin = service(servicePath, {
  debug: true,
  instanceDefaults: {
    userId: null,
    user: 'User',
    serverId: null,
    server: 'Server',
    status: 'PENDING',
  },
});
```

2 ) 
Use a find getter for the service to return the data from the store after dispatching a find to pull in the data.

3 ) 
Attempt to pull relationship, in this case server property (with the relationship). When logging the object that is pulled in the getter's returned array, I see the object containing a reactive getter for the relationship, in this case a "server" property. However, I when attempting to use the values from it, for example, the name of the server (the "name" property on the Server service) I get a object.server is undefined error. The relationship works fine if I get the individual server via the getter, however, I would like to be able to pull it from the find, rather than just get.

### Expected Behavior

I would expect this to actually provide the related service's properties/data, otherwise not even show the included property.

**Comment by marshallswain** [comment]
Hi @plunkettscott could you create a failing example?  The expected behavior is exactly how it works in my projects for all service methods.

**Comment by plunkettscott** [comment]
Hey @marshallswain,

Sorry for the huge delay. I've been on other projects. I've created a failing example on my Github account..

https://github.com/plunkettscott/feathers-vuex-issue

There is a README on how to make this fail. This might be my fault, I may be doing something wrong, however, this issue seems to be happening for every app I use this in (following the documentation closely).

Scott

**Comment by plunkettscott** [comment]
@marshallswain any ideas on this?

**Comment by plunkettscott** [comment]
Hey @marshallswain! Not sure if you've had a second to look at this or not. This is causing some delays on a project I am working on. I cannot see anything wrong with my setup in comparison to the documentation. Can you take a look at the demo project and tell me if I am doing something wrong?

**Comment by codybarr** [comment]
@plunkettscott I seem to be running into the same issue. Can't tell whether it's me not following the docs correctly or something else. 

Were you able to get this working?

**Comment by plunkettscott** [comment]
I did get it working. You have to actually provide the relationship in the data sent from the API. The FeathersVuex instance does not fetch the data to populate there.

**Comment by marshallswain** [comment]
That's correct.  It doesn't fetch the data for you, but that's an excellent feature idea.

**Comment by codybarr** [comment]
@plunkettscott Yeah, didn't realize I had to implement that on the server. Ended up using `populate` and `fastjoin`. Thanks for getting back to me.
