### ISSUE TITLE
Question: Can I use feathers vuex on client side without database model server side?

### ISSUE THREAD

**Issue by HarisHashim** [feathers-plus/feathers-vuex#129]
Let say I just create a custom feather service and then use sequelize to do raw MySQL statement query in the service hook.

And then I consume that service on client side using Feathers Vuex.

Will this work? What possible issue or bad/good practice regarding this?

TIA 
Haris

**Comment by marshallswain** [comment]
This will work just fine as long as you either have an `id` in each record, or set the `idField` to something unique on each record that you want inserted into the client-side store.

**Comment by marshallswain** [comment]
If you want the `instanceDefaults` to work, then you just have to have a consistent schema for all records returned from the same service.

**Comment by rayfoss** [comment]
@marshallswain https://codesandbox.io/s/xk52mqm7o I'm trying to demo an issue where 'current' and mapping the full state is reactive, but using `get` breaks reactivity. Code sandbox has everything we need... a demo on the ReadMe should improve the quality of this as a whole... and the quality for the issues

**Comment by HarisHashim** [comment]
Take sometime for me to understand the answer :D 

First of all I get this error in chrome (not in Firefox, which throw me of the scene for quite sometime).

```actions.js?1939:261 Uncaught (in promise) TypeError: list.forEach is not a function
    at Store.addOrUpdateList (actions.js?1939:261)
    at Array.wrappedActionHandler (vuex.esm.js?358c:704)
    at Store.dispatch (vuex.esm.js?358c:426)
    at Store.boundDispatch [as dispatch] (vuex.esm.js?358c:332)
    at local.dispatch (vuex.esm.js?358c:634)
    at handleResponse (actions.js?1939:31)
    at <anonymous>```

I thought this is because of pagination and to troubleshoot, I hardcoded a jason with pagination and that works. But it turns out that json also have data with id. The reason that work is because of id and have nothing to do with pagination.

And today, after reading your answer again. Finally I get it! Closing this issue. 

Thanks

**Comment by HarisHashim** [comment]
As note to other people, what works for me is as bellow

```
context.result = [
    {
        "uid": 1
        // bla bla bla
    },
    {
        "uid": 1
        // bla bla bla
    },
]
```
