### ISSUE TITLE
Save last query & timestamp by default 

### ISSUE THREAD

**Issue by rayfoss** [feathers-plus/feathers-vuex#131]
### Steps to reproduce
1. dispatch a `find` in one page of your app.
2. Navigate to another that effectively needs the same data.

### Expected behavior
We should have a way to tell how old the cache is and what query populated it. That would allow us to say, not run the query again if it was ran less than a minute ago.

### Actual behavior
The cache has no origin information, no information about whether the connection dropped since it was populated and no information about the query that populated it. Therefore, we have no guarantees about the data and are thus forced to implement our optimization or fire the potentially non-trivial query again.

Working with feathers-vuex is currently quite wordy... we should look for ways to cut down lines for the typical app.

### Proposed Solution
Lets add a property to the vuex state with 
```
last: {
  createdAt: 14245678921
  query: 'find'
  params: '{}'
}
```

**Comment by rayfoss** [comment]
I've found myself checking the cache and then fetching if not available a few too many times... it would be nice if feathers-vuex services came with an anyGet and anyFind action, which checks the cache for answers and if nothing is found, pulls from the web. A max age field would be a nice parameter as well.

```
getAssignment: async function () {
        let assignment = this.lazyAssignmentGet(this.$route.params.id)
        if (typeof assignment === 'undefined') {
          return this.assignmentGet(this.$route.params.id)
        } else {
          return assignment
        }
  },
  created () {
    ; (async () => {
      let assignment = await this.getAssignment()
     })()
  }
```

**Comment by rayfoss** [comment]
@marshallswain I'm using anyGet and anyFind in all my projects. Any get in particular drastically reduces network load and the risk of race conditions from sub components trying to getter/get when an upstream component hasn't finished action/get 

they are very small and work incredibly well... would you welcome a pull request for anyGet? I've found the use cases and benefits of anyFind less common.

```
// VUEX
export const standardCustomization = {
  actions: {
    anyGet: async function ({ commit, dispatch, getters }, args) {
      let entity = getters.get(args)
      if (typeof entity === 'undefined') {
        await dispatch('get', args)
        return getters.get(args)
      } else {
        return entity
      }
    },
    anyFind: async function ({ commit, dispatch, getters }, args) {
      let result = getters.find(args)
      if (result.total === 0) {
        await dispatch('find', args)
        return getters.find(args)
      } else {
        return result
      }
    }
  }
}
```

**Comment by marshallswain** [comment]
@rayfoss A PR would be great!  A new issue might be better if you feel like you might implement the main feature of this issue sometime.

**Comment by marshallswain** [comment]
I also like the idea of a `maxAge`-based cache.  As a baby step towards this, I've added a `createdAt` timestamp to the pagination data in `feathers-vuex@1.6.2`.

**Comment by marshallswain** [comment]
In the future, I'll look into using [can-query-logic](https://canjs.com/doc/can-query-logic.html) to implement smarter cacheing.

**Comment by rayfoss** [comment]
fun real world edge case:

Google play music will only get the playlist list once and pull from cache every time you go to the playlist list page. It will reactively add to the list, but if your laptop is asleep, you'll end up with missing playlists even though you've "browsed" back and forth between pages inside Google Play Music. 

AllGet would solve this, but it would be expensive for Google. AllGet([id, maxAge]) would fix the problem without hitting the server every time.

**Comment by marshallswain** [comment]
@rayfoss the new pagination object for each store now provides enough information to make this possible.  You get all sorts of info, now: https://feathers-vuex.feathers-plus.com/service-module.html#querying-with-find-pagination
