### ISSUE TITLE
 Object.defineProperty(Model, 'name', { value: modelInfo.name }) problem in 'strict mode'

### ISSUE THREAD

**Issue by ucokfm** [feathers-plus/feathers-vuex#136]
https://github.com/feathers-plus/feathers-vuex/blob/a3d26c6f174369c1649f7c078019b082864c884d/src/service-module/service-module.js#L106

When running it in global 'strict mode', this will be an error because 'name' is readonly property.
```javascript
Object.getOwnPropertyDescriptor(Model, 'name')
```
show
```javascript
{ value: 'Model',
  writable: false,
  enumerable: false,
  configurable: true }
```
Do we really need this name property value ('FeathersVuexModel') updated with model name? or is it safe if we just omit it?

**Comment by marshallswain** [comment]
Actually, I've found that it doesn't actually make any difference, so feel free to submit a PR to remove it.
