### ISSUE TITLE
Question about Authentication and token saved in localstorage

### ISSUE THREAD

**Issue by HarisHashim** [feathers-plus/feathers-vuex#140]
Base on this code in feathers-chat-vuex

```
const feathersClient = feathers()
  .configure(hooks())
  .configure(socketio(socket))
  .configure(auth({ storage: window.localStorage }))
```

Is there additional documentation about feathers-vuex saving token in localStorage. For instance event or state like isXxxxPending?

My problem is that when loading/refreshing page and there is jwt token saved in localStorage, my user object started with null and later change to valid user.

Since when user is null, I display a login screen and when user is valid i display a dash screen. So it would immediately display login for few second and then jump to dash.

My thinking is that, this is the transition between no user to jwt being decoded and then there is user.

Is there a way I can detect the starting of auth reading the token in local storage so that I can display loading when that happened and the hide loading when user is valid?

By the way I use same way as feathers-chat-vuex github sample. I.e. I watch for user as per bellow code:

 ```
watch: {
    // When the user is set, redirect to the Chat page.
    user (newVal) {
      if (newVal === undefined) {
        this.$router.replace({name: 'Login'})
      } else {
        this.$router.replace({name: 'Chat'})
      }
    }
  }
```

**Comment by kharhys** [comment]
> Is there a way I can detect the starting of auth reading the token in local storage so that I can display loading when that happened and the hide loading when user is valid?

This is more of a `vue.js` question than it is a `feathers` or `vuex` concern. One possible approach to achieving what you need would be adding a state variable to keep track of authentication as below
```javascript
data() {
  authAttempted: false
}
```
The variable `authAttempted` starts as `false` and is to be changed to true once authentication succeeds or fails, as below:
```javascript
  mounted () {
    this.$store.dispatch('auth/authenticate').catch(error => {
      if (!error.message.includes('Could not find stored JWT')) {
        console.error(error)
      }
    })
    .finally(() => { this.authAttempted = true; }) // add this line
  }
```
Then in your template use `v-if='authAttempted'` to determine whether to display or hide loader component.

I hope this helps.

**Comment by marshallswain** [comment]
Thanks, @kharhys for perfect answer and example.  This is definitely best handled in Vue.
