### ISSUE TITLE
Questions about usage of find action

### ISSUE THREAD

**Issue by romheroux** [feathers-plus/feathers-vuex#141]
Hello,

I'm new to feathers-vuex API, and I have a question about best practice in using it.
In feathers, I have a service that I call with query search param (like /service?search=toto), which is constructing a request to the database directly with the searched pattern. The db I use is not an official adapter for feathers, so it's better for the db performance.

So, in Vuex I can use a search input form by the following code for retrieving my searched datas : 

```
<template>
  <div>
    <result-list :results="results.data" />
  </div>
</template>

<script>

import { mapGetters, mapActions } from 'vuex'
import ResultList from './Results.vue'
export default {
  name: 'result-search-navbar',
  computed: {
    ...mapGetters('service', { findResultsInStore: 'find' }),
    results () {
      return this.findResultsInStore({ query: {} })
    },
    querySearch () {
      return this.$store.state.searched
    }
  },
  methods: {
    ...mapActions('service', { findResults: 'find' })
  },
  watch: {
    querySearch () {
      this.findResults({ query: { search: this.querySearch } })
    }
  },
  created () {
    this.findResults({ query: { search: this.querySearch } })
  },
  components: {
    ResultList
  }
}
</script>
```

`this.$store.state.searched` come from the form input.
The above code has the expected behaviour, but I'm questionning about best practices and the usage of the watch directive, I can't see how to avoid using it (by computed for example).

Can you explain me please ? Is it the right place for questionning ?
Many thanks for your great job !

**Comment by marshallswain** [comment]
This looks like it accomplishes the result you desire to achieve.  I wouldn't concern too much about using a watcher for something like this.
