### ISSUE TITLE
Issues using skipRequestIfExists

### ISSUE THREAD

**Issue by phenrigomes** [feathers-plus/feathers-vuex#143]
Did anyone issues using "skipRequestIfExists" on state/params? I used and the current object was not updated. I changed the code to:

```
      // If the records is already in store, return it
      var existedItem = getters.get(id, params);
      **if (existedItem && skipRequestIfExists) {**
        commit('setCurrent', existedItem);
        return Promise.resolve(existedItem);
      }
      return getFromRemote();
```

### Expected behavior
Update the current object

### Actual behavior
Does not update the current object

### System configuration

feathers-vuex 1.4.7

**Comment by jscottsf** [comment]
I found that it still uses the cached item if this setting is false. There seems to be a missing `return`.

```
      if (existedItem) {
        commit('setCurrent', existedItem)
        if (!skipRequestIfExists) getFromRemote() // Needs a return!!!
        return Promise.resolve(existedItem)
      }
```

**Comment by marshallswain** [comment]
Feel free to submit a PR.  I won't get to this any time soon.

**Comment by marshallswain** [comment]
I fixed this last night.  Thanks @jscottsf for the hint.  It's in the latest prerelease:

`yarn add feathers-vuex@2.0.0-pre.65`

`npm i feathers-vuex@2.0.0-pre.65`
