### ISSUE TITLE
Model.clone() broken for namespaced services (PR attached)

### ISSUE THREAD

**Issue by metareason** [feathers-plus/feathers-vuex#145]
### Steps to reproduce

Setup a service in the Vuex store with a namespace: eg
```js
  plugins: [
    service('asset-types', {
      namespace: 'assetTypes',
    }),
```

Try to .clone() a Model from that namespaced service
```js
      const { AssetType } = this.$FeathersVuex;
      const assetType = new AssetType();
      this.assetTypeCopy = assetType.clone();
```

### Expected behavior

The model is cloned.

### Actual behavior

Error: service-module.js?9849:153 Uncaught (in promise) TypeError: Cannot read property 'keepCopiesInStore' of undefined

### System configuration

**Module versions** 1.4.8

Looks like it is a 1 line fix in service-module.js
change
```js
if (store.state[Model.servicePath].keepCopiesInStore) {
```
to
```js
if (store.state[namespace].keepCopiesInStore) {
```

**Comment by metareason** [comment]
PR in #146 with a fix thanks!

**Comment by marshallswain** [comment]
Wow.  Thank you for this.  I've been busy for a few days, and it's so good to see awesome PRs come in while I'm out.  Thanks a million.

**Comment by marshallswain** [comment]
I have a few PRs to review, but I'll merge this in as soon as possible.

**Comment by barata0** [comment]
Same error here.
