### ISSUE TITLE
Limit of list

### ISSUE THREAD

**Issue by jafri** [feathers-plus/feathers-vuex#149]
I have a websocket that receives new data every 0.5 seconds

If a user is on the page for lets say 5 minutes, that is 600 items in the list stored on Vuex. 

Is there a way to set a maximum on the # of records stored?

**Edit:** Something like a max TTL would work too

**Comment by marshallswain** [comment]
This is not currently built in, nor do I have plans to build it.  You can accomplish something like this pretty easily using a setInterval in your store, though.  Or you could use a Vue watcher on the `ids.length` property in the service's data store and when a new one comes in, drop an older one.
