### ISSUE TITLE
replaceItems true ignores isFeathersVuexInstance checking

### ISSUE THREAD

**Issue by elaijuh** [feathers-plus/feathers-vuex#151]
I was trying to patch an item which has an array object, due to `lodash.merge`, the update will not reflect in the `list` getter. So i set `replaceItems` to true to fully replace the item in store, but it seems replace with a plain object but not `FeathersVuexInstance` which is not consistent. [Refer here](https://github.com/feathers-plus/feathers-vuex/blob/master/src/service-module/mutations.js#L38).

I will suggest to check make replace item feathers instance, should I PR on this?

**Comment by marshallswain** [comment]
Can you try this with the latest version?  `1.5.0`  It's possible that this has been fixed in one of the landed PRs.

**Comment by marshallswain** [comment]
I'm pretty sure this is fixed.  Please reopen if you find otherwise.
