### ISSUE TITLE
[BUG] Patch $pull wont update store

### ISSUE THREAD

**Issue by guzz** [feathers-plus/feathers-vuex#152]
### Steps to reproduce

[1] Have a model with a property that is an array of objects.
[2] Create a FeathersVuex model and clone it.
[3] Splice the array, save and commit the clone

### Expected behavior

The store should update with the database update

### Actual behavior

The database is updated but it doesn't update the store

It does work when I don´t use the clone and make the update directly in the FeathersVuex model and save it

### System configuration

**Module versions** 

latest

**NodeJS version**:

node 8 and 10

**Operating System**:

linux debian 9

**Comment by marshallswain** [comment]
This should be fix in the changes found in this issue: https://github.com/feathers-plus/feathers-vuex/issues/189

Please reopen if not.
