### ISSUE TITLE
Get action not adding result to store?

### ISSUE THREAD

**Issue by homerjam** [feathers-plus/feathers-vuex#153]
Hi!

According to the [docs](https://feathers-plus.github.io/v1/feathers-vuex/service-module.html#get-id-or-get-id-params) the store should be updated when dispatching the `serviceName/get` action, however I've noticed this isn't the case. The result is available via `store.getters.['serviceName/getCopy']` but not under `state.serviceName.keyedById` as expected.

Am I mistaken or could this be a bug?

Thanks,
James

### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by marshallswain** [comment]
Did you set the `idField`?  This is expected behavior if the record does not have an id field that matches the `idField` configuration property.  Feel free to reopen if this is still an issue after checking that.
