### ISSUE TITLE
v1.4.5 breaks $select, i.e. returns empty fields

### ISSUE THREAD

**Issue by gpolitog** [feathers-plus/feathers-vuex#154]
After updating to v1.4.5 or higher, $select returns records with empty fields.

### Example

this.findGetter({ query: { $select: ['field1', 'field2'] } })

using v1.4.4- correctly returns

[
{ field1: "value1", field2: "value2" }
{ field1: "value1", field2: "value2" }
]

but v1.4.5+ returns

[
{ field1: undefined, field2: undefined }
{ field1: undefined, field2: undefined }
]

**Comment by marshallswain** [comment]
Thank you for reporting this.  This is fixed in the latest version.

`npm i @feathers-vuex@1.6.1`
