### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by joeinnes** [feathers-plus/feathers-vuex#156]
Also logged with Feathers: https://github.com/feathersjs/authentication-client/issues/108
@petebytes has created a repo: https://github.com/petebytes/trello-clone.git

### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [x] Tell us what broke. The more detailed the better.
- [x] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
When dispatching a create action, the access token should be populated onto the request, and the request sent to the server for processing.

### Actual behavior
When dispatching a create action, there's an error when trying to populate the access token, and the request does not get sent to the server:

```
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at Object.eval (populate-access-token.js?39da:9)
    at promise.then.hookObject (hooks.js?8408:142)
```

In particular, it seems to be the case that the hook.params is undefined, so when calling Object.assign, it fails.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
```
  "dependencies": {
    "@feathersjs/authentication-client": "^1.0.4",
    "@feathersjs/feathers": "^3.2.1",
    "@feathersjs/rest-client": "^1.4.3",
    "@feathersjs/socketio-client": "^1.1.2",
    "axios": "^0.18.0",
    "feathers-vuex": "^1.4.8",
    "hellojs": "^1.17.1",
    "socket.io-client": "^2.1.1",
    "vue": "^2.5.17",
    "vue-router": "^3.0.1",
    "vuetify": "^1.0.19",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@babel/polyfill": "^7.0.0-beta.49",
    "@vue/cli-plugin-babel": "^3.0.1",
    "@vue/cli-plugin-eslint": "^3.0.1",
    "@vue/cli-service": "^3.0.1",
    "@vue/eslint-config-standard": "^3.0.1",
    "lint-staged": "^7.2.2",
    "vue-cli-plugin-vuetify": "^0.1.6",
    "vue-template-compiler": "^2.5.17"
  },
```

**NodeJS version**: 9.4.0

**Operating System**: macOS High Sierra

**Browser Version**: 68.0.3440.106 (Official Build) (64-bit)

**React Native Version**: Not using React Native

**Module Loader**: vue-cli-service (ie: webpack)

**Comment by joeinnes** [comment]
Seems a change has been implemented upstream requiring you to pass params:

https://github.com/feathersjs/authentication-client/issues/108#issuecomment-421334346

**Comment by wdmtech** [comment]
Just came across this myself. Calling

`todo.save()` on a FeathersVuexModel caused this error, but

`todo.save({})` works

**Comment by joeinnes** [comment]
Is this also thrown from the populateAccessToken.js file in the Feathers
authentication client? If so, I put in a PR earlier today for this.
