### ISSUE TITLE
conflict merging as part of this package

### ISSUE THREAD

**Issue by ndamjan** [feathers-plus/feathers-vuex#16]
**Proposal: implement some conflict merge strategies for cases of simultaneous editing of the same object when feathers-reactive is used.**

For example: Alice and Bob open the same record. Alice changes a field Title and Bob changes field Content. Depending on who saves first, other person loses his work as his current record is replaced. Another case is that Alice deletes the record while Bob is working on it. 

Currently I implemented such detection logic in a mixin and a decision mechanism on which version to keep, but maybe it would be good to have it as part of this package.

What do you think?

**Comment by marshallswain** [comment]
If the detection logic is expensive, we might want it behind a flag.  We could add a `conflicts` key to each service's vuex store.  The UI part we would probably want to keep separate.

**Comment by ndamjan** [comment]
Exactly like you wrote - my detection logic is in functions (from mixin) and the UI (a separate Vue component) relies on the local state to show type of change and actions which could be taken. Once my implementation is properly tested I will merge it with the package.

**Comment by marshallswain** [comment]
I have no plans for this right now, so I'm going to close until it becomes more important on my end.  Feel free to reopen if you start working on it.
