### ISSUE TITLE
Sort by decimal doesn't work in the reactive getters

### ISSUE THREAD

**Issue by kbugala** [feathers-plus/feathers-vuex#160]
### Steps to reproduce

Sorting in the reactive getters doesn't work properly for decimal fields (mongoose adapter in FeathersJS).

When testing the Find query with sort via PostMan or via Vuex action it works as expected.

**Steps to reproduce** 

```
import { mapState, mapMutations, mapActions } from 'vuex'

export default {
data () {
    return {
      vm: {
        limit: 10,
        skip: 0,
        total: 0
      },
user: {
_id: '12345'
}
    }
  },
computed: {
     ...mapGetters('transactions', {
       findTransactionsInStore: 'find'
     }),
     transactions () {
       return this.findTransactionsInStore({
         query: {
           $sort: {
amount: -1 // amount is decimal
},
           $skip: this.vm.skip,
           $limit: this.vm.limit,
           userId: this.user._id
         }
       })
     }
}
}
```

**Query via the Vuex action works:**

```
import { mapState, mapMutations, mapActions } from 'vuex'
export default {
  data () {
    transactions: [],
vm: {
        limit: 10,
        skip: 0,
        total: 0
      },
user: {
_id: '12345'
}
  },
methods: {
  ...mapActions('transactions', {
      findTransactionsInServer: 'find'
    })
},
getTransactions () {
      this.findTransactionsInServer({
        query: {
          $sort: {
amount: -1 // amount is decimal
}
          $skip: this.vm.skip,
          $limit: this.vm.limit,
          userId: this.user._id
        }
      }).then(response => {
        this.transactions = response
      })
    }
}
```

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
"feathers-vuex": "^1.4.8"

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by marshallswain** [comment]
Can you try this out with the latest release?  A new version of the `sift` package was published that may have fixed this.

**Comment by marshallswain** [comment]
I've added tests that assure this is working properly in the latest pre-release.  It is likely working just as well in the current `latest` version, as well.
