### ISSUE TITLE
[Feature] Model Specific Computed Properties

### ISSUE THREAD

**Issue by jchamb** [feathers-plus/feathers-vuex#163]
In a few cases i've found my self really wishing there were model specific computed properties. 

Basic example:
Post with Comments. Have a computed property on the Post model to cache number of unique users in the comment discussion.

eg: Post.numOfCommentors

Easy work around for now i typically wrap a model from a list into a vue instance to pass to a template that I need the getters in. Doing so is definitely dirty and hacky so it would be great to get this worked directly in so they are computed as soon as a model is created.

**Comment by marshallswain** [comment]
This is already possible using es5 accessors.  You can use both getters and setters:

```js
service('post', {
  instanceDefaults: {
    description: '',
    isComplete: false,
    comments: [],
    get numberOfCommenters () {
        // Put your logic here.
    },
    set someOtherProp () {
        //  Setters also work
    }
  }
})
```

**Comment by marshallswain** [comment]
I've added this to the documentation, here: https://feathers-plus.github.io/v1/feathers-vuex/common-patterns.html#Model-Specific-Computed-Properties

Thanks!
