### ISSUE TITLE
pushing update logic to background worker

### ISSUE THREAD

**Issue by ndamjan** [feathers-plus/feathers-vuex#17]
With some larger number of records kept in store the UI becomes unresponsive during updates. Some quick profiling revealed that the addOrUpdateList function is taking most time.

**Proposal**: put the list manipulation logic to background worker, add some state like `newDataProcessing` to indicate that something is going on.

**Comment by marshallswain** [comment]
Absolutely.  This will make a big difference for queries with larger responses.

**Comment by rayfoss** [comment]
I'm also running into this issue. I'm planning to add a rawFind action to my services that skips adding records to the local store.

I'm planning to process the data in a web worker. I want to have capacity for 4gb of data in RAM.

**Comment by marshallswain** [comment]
This is definitely one of the first performance enhancements on the list after I finalize getting the `pagination` branch moved into the `typescript` branch.

**Comment by marshallswain** [comment]
I'm actually going to close this.  Even with data-intensive applications, optimizing queries with supportive pagination is an ideal solution for the goal in mind here (minimal frozen UI).  I might change my mind if I can find a scenario where this is really required.
