### ISSUE TITLE
Enhancement: Auth Module: split the response handler to a separate action

### ISSUE THREAD

**Issue by rayfoss** [feathers-plus/feathers-vuex#170]
https://github.com/feathers-plus/feathers-vuex/blob/21a95d1c7cc466254a251e1eab4232b9a0804e39/src/auth-module/actions.js#L11

When pretending to be online it's useful for everything to seem normal... including auth. If the response handler for auth were a separate action, I could just call it with the token and it would set the state to be the same as if feathers client actually got a response from the server.

**Comment by marshallswain** [comment]
I'm going to close this since it's fixed in the pre-release.
