### ISSUE TITLE
auth.user not updated with replaceItems: true

### ISSUE THREAD

**Issue by mrfrase3** [feathers-plus/feathers-vuex#174]
### Steps to reproduce

If you set `replaceItems: true` on the users service, when `updateItems` is run for the currently authenticated user, `auth.user` is not updated to the new object.

It also looks like the return of the `get` action is also the previous value.

I believe this is possibly the issue for #166 

### Expected behavior
`auth.user` is not updated
### Actual behavior
`auth.user` should be updated

feathers-vuex version: 1.6.2

**Comment by mrfrase3** [comment]
looking at the `get` action
```js
      // If the records is already in store, return it
      const existedItem = getters.get(id, params)
      if (existedItem) {
        commit('setCurrent', existedItem)
        if (!skipRequestIfExists) getFromRemote()
        return Promise.resolve(existedItem)
      }
      return getFromRemote()
```

shouldn't it be:
```js
if (!skipRequestIfExists) return getFromRemote()
```

**Comment by marshallswain** [comment]
I'll accept a PR for this, but doing this myself is not an option, currently.

**Comment by mrfrase3** [comment]
So, I've written a fix for these issues, but I came across a problem whilst running the unit tests:
```js
// Make a request to an existing record and return the existing data first, then update `keyedById`
              todoState.keyedById = {
                0: { id: 0, description: 'Do the FIRST' }, // twist the data to see difference
                1: { id: 1, description: 'Do the second' }
              }
              actions.get.call({$store: store}, [0, {}])
                .then(response3 => {
                  expectedKeyedById = {
                    0: { id: 0, description: 'Do the FIRST' },
                    1: { id: 1, description: 'Do the second' }
                  }
                  assert(response3.description === 'Do the FIRST')
```
This means the get action returning the existing item from the store was intentional. But this makes no sense in a practical setting:
  1. One would expect this from the getter that does local calls, not the action that does the server calls.
  2. If I already have the id of the item to call this request, then I most likely already have the existing item, thus returning it is redundant.
  3. In order to get the new value, I would need to call this, then write spaghetti magic code that does an arbitrary timeout to wait for the new item to be populated.

It makes sense to go ahead with this fix, but because it was the expected functionality, I fear this might be code-breaking for some existing apps. Then again, it would be the devs fault for not testing their code after performing a dependency update...

Thoughts?

**Comment by mrfrase3** [comment]
hey @marshallswain, is there any news on this?

**Comment by marshallswain** [comment]
I somehow missed your message on Dec 13.  I will close this, now.  

I actually found that test code you highlighted and scratched my head a bit on it last night.  It didn't feel right.  So I fixed it.  ;)  There was a stray promise that wasn't being `await`ed.  Thanks!
