### ISSUE TITLE
Instance property values are partially saved sometimes when a use close page too fast

### ISSUE THREAD

**Issue by flight9** [feathers-plus/feathers-vuex#175]
I have a model `Image` to trace the state of an uploading image. 
I use following codes to update an instance of model in one step of my uploading:
```
  // update the photo state on the server
  imageCopy.wx.serverId = serverId;
  imageCopy.state = 'wxUploaded';
  await imageCopy.save();  // there is a hook(after-hook) on server side, may take a period of time
```
The above always works fine when a user is patient to wait for the end of uploading. 
But if he is not that patient and close the page too fast(before uploading has finished), something goes wrong.
On server side(feathers), I noticed, in the after-hook, sometimes the `state` got saved, but the `wx.serverId` not:
```
{
    "_id" : ObjectId("5bd80383f3255884c04f828a"),
    "wx" : {
        "localId" : "weixin://resourceid/a6d720de45354e900f03b5b8263a47ce"
        // "serverId" is missing
    },
    "type" : "photo",
    "state" : "wxUploaded",  //got saved
    "userId" : ObjectId("5bc068f3e9b494579abe388c"),
    ...
}
```
I'm curious why this will happen and no error or warning occurs and how to avoid this.

version: feathers-vuex@1.4.8

**Comment by marshallswain** [comment]
I imagine the entire request isn't finishing, which would mean the promise is not resolving.  You might be able to add a check to make sure the request's promise has resolved before you let anybody navigate away from the page.  You can get access to the promise in the return value of the action.  This is outside the scope of feathers-vuex, so I'm going to close this, but please reopen if you determine that there's something that needs to be updated to support what you're trying to do.

**Comment by flight9** [comment]
@marshallswain thanks for reply. I've found the cause, it's another lib that do not return serverId correctly, not feahters-vuex.

**Comment by marshallswain** [comment]
Thanks for the update.  👍
