### ISSUE TITLE
Not working in IE 11

### ISSUE THREAD

**Issue by cemevren** [feathers-plus/feathers-vuex#177]
I've created a sample project with latest vue-cli and added feathers libraries. Error on ie11 attached

api/feathers-client.js
```
import $config from '@/config'
import feathers from '@feathersjs/client'
import io from 'socket.io-client'
const socket = io($config.feathersServer, { transports: ['websocket'], upgrade: false })
const feathersClient = feathers()
feathersClient.configure(feathers.socketio(socket));
feathersClient.configure(feathers.authentication());
export default feathersClient
```

store/index.js
```
import Vue from 'vue'
import Vuex from 'vuex'
import feathersVuex from 'feathers-vuex'
import feathersClient from '../api/feathers-client'

const { service, auth, FeathersVuex } = feathersVuex(feathersClient, { idField: '_id' })

Vue.use(Vuex)
Vue.use(FeathersVuex)

export default new Vuex.Store({
    state: {
  
    },
    mutations: {
  
    },
    actions: {
  
    }
})
```

![virtualbox_ie11 - win81_06_11_2018_11_58_47](https://user-images.githubusercontent.com/1059195/48053371-9cc39f00-e1bb-11e8-812b-d64257a8f670.png)

**Comment by marshallswain** [comment]
Hmm.  Any idea where the problematic character lies in the codebase?

**Comment by stwessl** [comment]
@marshallswain it's in the @feathersjs/commons/lib/utils.js file

**Comment by marshallswain** [comment]
I'm going to close this, since I have no intention to support IE11 in any apps that I build.  If anybody would like to champion this issue, I believe all that is required is proper polyfill support for feathers to work in IE11, in general.  A PR to the docs on how to set it up would be great for those who are interested in IE11 support.  I will continue to focus on the core functionality.  If a situation arises where IE11 support is required for my work, I will gladly implement it.  In the meantime, thank you for opening the issue so I am at least aware of it.

**Comment by stwessl** [comment]
@marshallswain i actually tried to fix this

You would have to remove your dependency on the server-side version of @feathersjs/common, unfortunately, the IE friendly @feathersjs/client does not have the functions you are depending on for this implementation, meaning that you would need to copy the functions you are depending on from @feathersjs/common and add it to this project

I'll do this when I have time and are "forced to" support IE11

**Comment by cemevren** [comment]
Hi there,

I've finally found a way. It's working on the production in couple of days. I'll create a clean project as a sample and share as soon as possible.

**Comment by KDanila** [comment]
> 
> 
> Hi there,
> 
> I've finally found a way. It's working on the production in couple of days. I'll create a clean project as a sample and share as soon as possible.

Hi!
I have the same exception. Can you help me? How do you resolve this problem?

**Comment by OnnoGabriel** [comment]
@stwessl and @cemevren, did you ever published a sample project with IE support?
