### ISSUE TITLE
Add toJSON method to FeathersVuexModel class

### ISSUE THREAD

**Issue by NickBolles** [feathers-plus/feathers-vuex#179]
### Steps to reproduce
- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

I'm not exactly sure what is causing this, besides that I'm doing SS authentication, and trying to store the 
```
‼ warn Cannot stringify arbitrary non-POJOs FeathersVuexModel
```

I think this could be resolved by adding a `toJSON` method on the class. Plus in-general it's a good practice. 

https://github.com/nuxt-community/devalue/pull/1

**Comment by DreaMinder** [comment]
So is this resolved by adding toJSON? Because I still got warnings
`"feathers-vuex": "^1.6.2",`

**Comment by NickBolles** [comment]
@DreaMinder I'm not sure that there's been another release to non since this change
@marshallswain do you know?

**Comment by marshallswain** [comment]
Lots of them in the `pre` channel

`npm i feathers-vuex@pre`
