### ISSUE TITLE
Service module overwrites existing service.Model

### ISSUE THREAD

**Issue by j2L4e** [feathers-plus/feathers-vuex#183]
The `FeathersVuexModel` is saved in `service.Model` on setup (see https://github.com/feathers-plus/feathers-vuex/blob/master/src/service-module/service-module.js#L90). Unfortunately, there are services that save their own Model in `service.Model`, e.g. `feathers-sequelize` and `feathers-nedb` are two that I know about.
These services are rendered unusable by `feathers-vuex`.
The problem would be solved easily by using a more unique property name than `Model` or by using a `Symbol`.

I work around this now by using proxy services.

**Comment by marshallswain** [comment]
Of course!  Thank you for pointing this out.  I've published `v1.7.0-pre.42`  (`npm i feathers-vuex@pre`) which moves the property to `service.FeathersVuexModel`, which should avoid conflicts.

**Comment by marshallswain** [comment]
Since you have a workaround, I'm going to close this issue.
