### ISSUE TITLE
featherjs return from get before hook is null

### ISSUE THREAD

**Issue by dkebler** [feathers-plus/feathers-vuex#187]
I have a feathers before hook for get (on a service) which when fed a special id 'schemas' returns the collection's schemas object instead of an actual object of the service collection.  This all has been working great from my browser client with a standard direct call setup using a featherjs socket client.  (FYI, The schemas are needed to generate forms that display/edit the service's collection.)

Now instead of baking my own per page "local" store (which works fine) I thought I'd try featherjs-vuex where I could make one set of action "find" initially for all my services, get everything loaded and then use the feathersjs-vuex getters to do my filtering and sorting locally  (currently I make clones of the retrieved data and use lodash filter and sorting)

My only issue is that now my clever way to get the schemas to the browser is broken.   featherjs-vuex returns nothing :(

`await this.$store.dispatch('circuits/get', ['schemas', {}]))`
returns nothing
but 
`await this.$store.dispatch('circuits/get', ['anexistingid', {}]))`
returns that object/record from the collection

Is there some issue with hooks or the way I am using them and feathers-vuex?

Here is my get before hook.
```
// Sends back corresponding attached schemas for get when id 'schema' is used with get from client
module.exports = function () {
  return function(hook) {
    if (hook.id === 'schemas') {
      // setting hook result will send schemas to client and bypass service get
      hook.result = hook.service.Model.schemas
    console.log('getting schema', hook.result)
    }
    return hook
  }
}
```
the console.log confirms that the feathersjs-vuex dispatch get command with id of 'schema' does fire the hook on the feathersjs server but as I said nothing is returned.

-------------

Also...If this did work (which it currently doesn't) I assume that the local state would get the schema object.  Is there a way in the dispatch call to tell it to not put the result in the store?

using node 11+
latest vue/vuex and your package
also using the quasar-framework

**Comment by J3m5** [comment]
You must set an id to the result object, otherwise feathers-vuex will discard it as it use the ids to perform queries.
See #182 and #129.

**Comment by dkebler** [comment]
@J3m5  Thanks for suggestion that worked!  I just added a _id prop of "schema" to each schema and they loaded.  Then immediately I commited a copy to its own store and in the commit I remove it from the collection's store. I suppose one could leave it in the collection but you'd have to make sure all queries to the store filtered that _id:'schema'.

Great! now I can drop the plain socket client all together.

Yes the documentation should maybe mention this issue and maybe how to handle the returned record like I did.

Here is what I did

```javascript
export async function loadSchemas (store, db) {
  let gets = store.state.services.map(s => { return store.dispatch(`${s}/get`, 'schemas') })
  // warning: if any get is undefined no error is thrown from promise.all
  let [err, schemas] = await to(Promise.all(gets))
  if (err) return err
  store.commit('schemas', [store.state.services, schemas])
  return schemas
}

// then the store commit is

    schemas: (state, schemas) => {
      if (Array.isArray(schemas[0])) { // if array then this just loaded from back end
        schemas[0].forEach((service, index) => {
          state.schemas[service] = schemas[1][index]
          store.commit(`${service}/removeItem`, 'schema') // so remove from state collection
        })
      } else state.schemas[schemas[0]] = schemas[1]  // just locally updating a schema
    },

**Comment by dkebler** [comment]
Well,

If you notice I use the returned gets (not from the store afterwards).  
Why can't dispatch just return the result (as it already does) but NOT write it to the store if there is not id property rather than dropping it.  Nothing horrible about that is there??? and then all like myself that use get as a way via server hooks to feed other "stuff" to the client can do so without having to (1. use a whole other client, or 2. deleting the just "got" record from the store as I did above)

Is there some practical reason why this can't be so?

**Comment by marshallswain** [comment]
@dkebler this is actually a great idea, and was simple to implement.  Please try out the latest pre-release (`npm i feathers-vuex@pre`)  You'll need to make sure that `v1.7.0-pre.43` or higher is installed.  If the data doesn't have an id, it won't get added to the store, and you'll get a completely normal response like you'd expect from the regular Feathers client.
