### ISSUE TITLE
updateItem mutation should create getter/setter when property to be updated is new

### ISSUE THREAD

**Issue by dkebler** [feathers-plus/feathers-vuex#190]
Not that I can't add my own patch mutation by merging a copy of current item state with my patch and then use updateItem but was there a reason that `patch` was not included as one of the service mutations like it was for actions.

https://feathers-plus.github.io/v1/feathers-vuex/service-module.html#Service-Mutations

```javascript
      let patched = Object.assign({}, this.$store.getters[`${this.service}/get`](update._id), { [update.prop]: update.value })
      console.log('item as patched', patched)
      this.$store.commit(`${this.service}/updateItem`, patched)
```

in my use case I don't dispatch until user wants to save an item that way they can also revert to last saved/dispatched (i.e. the store), but I need to update the store so my form gets rerendered (thus a mutation).

**Comment by dkebler** [comment]
for those needing it here is a mutation patch for any service.
Any reason `patch` can't be added to mutations?  would PR be accepted?

```javascript
    patch: (state, patch) => {
      console.log('applying patch', patch)
      let patched = Object.assign({}, store.getters[`${patch[0]}/get`](patch[1]._id), patch[1])
      console.log('item as patched', patched)
      store.commit(`${patch[0]}/updateItem`, patched)
    },
```

here is example call from a vue page method

```javascript
    this.$store.commit(`patch`, ['myservicename', patch])
```
where patch is object that must include `_id:`

**Comment by dkebler** [comment]
After digging a bit deeper the store state has a property 
```javascript
replaceItems: false, // When set to true, updates and patches will replace the record in the store instead of merging changes
```
which (after a test) I can confirm that `updateItem` will work like a `patch`

It turns out that the issue have been that if the service model doesn't already have a property and then you try to `updateItem` with that property it will store the value and NOT create a getter/setter for it first then save it.  Thus that "new" property will not be reactive.   

So I guess the issue is really can UpdateItem create a getter/setter for a new property then set it??   

I am going to change the issue name to reflect this

**Comment by marshallswain** [comment]
@dkebler thanks for opening the issue.  @metareason has already explained the intended uses to take care of your use cases.  Please try them out and let me know if there's something that needs updating.  If it all looks good, feel free to close this issue.

**Comment by marshallswain** [comment]
The changes from this commit should have fixed this issue: https://github.com/feathers-plus/feathers-vuex/issues/189

Please reopen this if you find there is still an issue @dkebler
