### ISSUE TITLE
Patch is broken in @pre

### ISSUE THREAD

**Issue by NickBolles** [feathers-plus/feathers-vuex#195]
### Steps to reproduce
Use v 1.6.2 and install the plugin with Vue.use. Then use the plugin to do this.$FeathersVuex.user({something:"asdf"}).patch({})

It works great. 

Now update to @pre and it will fail with "no method 'patch'"

### Expected behavior
Patch should continue working

### Actual behavior
Error thrown

https://github.com/feathers-plus/feathers-vuex/compare/21a95d1c7cc466254a251e1eab4232b9a0804e39...data-component

I think this is the comparison of code. Not quite sure what's causing it cause nothing significant seems to be changed. I think I'll have to retest in the morning when I have a bit more awareness.

**Comment by NickBolles** [comment]
It looks like this is because the user is already in the store, so the constructor for the service returns the store data instead of a FeathersVuexModel instance.

I can work around this by just setting everything onto a blank instance, but IMO new this.$FeathersVuex.serviceName() should always return a FeathersVuexModel

![image](https://user-images.githubusercontent.com/7891759/52652611-143c5500-2eb4-11e9-8401-86fc7ce85e08.png)

**Comment by NickBolles** [comment]
Actually this is related to #198

**Comment by marshallswain** [comment]
This should now be fixed for every scenario EXCEPT Nuxt with SSR.

**Comment by marshallswain** [comment]
I'm going to close this since it's fixed in the pre-release.
