### ISSUE TITLE
Basic usage breaks in Nuxt SSR

### ISSUE THREAD

**Issue by Palivonas** [feathers-plus/feathers-vuex#196]
FeathersVuex breaks on Nuxt SSR with the most basic usage.

`$FeathersVuex.Todo` items load fine on client side (open root, then click the link to `/todos`);

On server side (refresh `/todos`), infinite recursion happens in `toJSON` in `feathers-vuex/lib/service-module/model.js:237`.

### Steps to reproduce

See this repo/branch for a reproduction:
https://github.com/Palivonas/feathers-vuex-bug-reproduction/tree/models-tojson-nuxt-ssr

FeathersVuex `1.7.0-pre.54`.
Node 10 and 8 tested, app created using `create-nuxt-app`.

**Comment by NickBolles** [comment]
Woops... That's my fault probably. Why does infinite recursion happen? Is there a circular reference?

**Comment by marshallswain** [comment]
There's likely a circular reference in the instanceDefaults that's causing this.  The fix is likely to make toJSON more intelligent so it excludes props that are getters, setters, or other models.

**Comment by NickBolles** [comment]
Shoot. That's not super simple to do, is it? I've experienced complications in doing that in the past.

**Comment by marshallswain** [comment]
It's way simple. Each Model already keeps an internal list of relationships, so that will just need to be made accessible to the toJSON method.

**Comment by NickBolles** [comment]
Sweet. Well I can try to look at this at some point. Thanks for the reproduction repo @palivonas!

**Comment by Palivonas** [comment]
Just a tip to make your work easier: run `node ./node_modules/.bin/nuxt` in your IDE so you can place breakpoints and stuff.

**Comment by marshallswain** [comment]
Yeah, this is the same spot to fix the getters.

**Comment by Palivonas** [comment]
Sorry for the later reply. Thanks for the effort @NickBolles, this does fix some things! Not completely, unfortuntely.

Updated the reproduction repo. Getter data gets included in `toJSON` result, therefore SSR still breaks completely and models can't be stringified on client side either. Apart from breaking, including getter data in toJSON is undesirable, I think.

Maybe this could be fixed by listing properties from `instanceDefaults()` and excluding any getters and methods present in there?

I also realized another (bigger?) SSR-related issue. FeathersVuex models don't only lack `instanceDefaults` methods when loaded via SSR - they don't have any model methods (clone, save, etc.). Methods get serialized into empty objects though.

I guess objects in the pre-rendered state should be wraped in FeathersVuex constructors on load somehow?

**Comment by NickBolles** [comment]
@Palivonas the issue with models loaded after ssr is a separate issue from tojson. (Classrs and getters/setters/methods can't be serialized)

We can look at wrapping everything in the store again, which should restore all getters/setters/methods. 

What getters are you seeing being included that shouldn't be? Maybe we need to include an option to overide/extend the tojson implementation?

**Comment by Palivonas** [comment]
@NickBolles Yeah, SSR data wrapping is out of scope for this issue, agreed.

What I mean about undesirable data in JSON is simply instanceDefaults getters being included in toJSON result. In the example repo `User` model has a `todos` getter, which finds all todos in store belonging to the user. `Todo` has a `user` getter (which is commented out as the circular structure breaks toJSON currently). These are handy to use in rendering or some logic (that's why it was introduced to FeathersVuex after all).

When I patch a model (or do anything else requiring its serialization), I wouldn't expect or want all the relationships and virtual properties (which are all defined as getters) to be included in the JSON. Validation on API side, unnecessarily large payloads, unintentionally exposing sensitive data (like the user object), duplicate objects for the same record in state loaded from SSR.

But maybe I'm approaching this wrong? Let me know what you think.

**Comment by NickBolles** [comment]
Yea. I agree. But I'm not sure what the default state is, of a JavaScript class with a getter only. 

You can always do object.defineproperty with enumerable false to define the getter, which should make the property non enumerable and ignored by the merge function, and thus the toJSON method.

**Comment by Palivonas** [comment]
`enumerable: false` is a great idea actually. So simple that I'm ashamed I didn't think about it 😅 It solves both the circular reference problem and undesirable computed data being present in JSON.

No need to reopen this issue then. Model instantiation can be tackled with in the other issue. Thanks again for the help!

**Comment by marshallswain** [comment]
@NickBolles @Palivonas I know one of you mentioned docs, recently.  I'm not sure which issue it was in.  I've moved the docs into this repo if there's anything to update.  Just check out the docs directory.  You can build locally with `npm run docs:dev`, since it's a vuepress site, now.

**Comment by NickBolles** [comment]
@Palivonas BTW, Check out this runkit for some tests on classes/properties and combinations of defineProperty.

https://runkit.com/nickbolles/lodash-merge-and-defineproperties

> note: the rest is kinda for self-documentation and should move into the feathers-vuex docs at some point


Basically getters should, by default be `enumerable: false`, ([another source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Description)) whether they are setup on a class, or without passing the `enumerable` key to the defineProperty call.  So in order to have something from instanceDefaults (or any javascript object/class) serialize to json you have to set `enumerable: true`.

For Feathers-Vuex, this means that instance defaults should be setup with [`Object.defineProperty`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty), or [`Object.defineProperties`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties) calls. This can be before or after the object is constructed (see [modifying a property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Modifying_a_property))
