### ISSUE TITLE
SSR state records are not FeathersVuex models

### ISSUE THREAD

**Issue by Palivonas** [feathers-plus/feathers-vuex#198]
Records loaded into state from Nuxt SSR are queryable with FeathersVuex `findInStore`, `getFromStore`, but they are plain objects and not FeathersVuexModel instances, therefore lacking any default methods (`save`, `clone`, etc.). Custom methods defined in `instanceDefaults` get serialized into plain empty objects.

This breaks any page where SSR-loaded records are present and FeathersVuex model method needs to be used on them. Kinda breaks getters as well, as they are no longer actual reactive getters, but plain objects computed on server side.

Serializing methods is not possible, obviously. At some FeathersVuex initialization step (or state watching?) those records should be wrapped in FeathersVuexModel I think.

Methods getting serialized into objects should probably be handled in toJSON, not app startup (see #196). Though defining them with `enumerable: false` could also be a solution.

Version `1.7.0-pre.56`

**Comment by NickBolles** [comment]
~~I'm a little confused by this part~~
> Custom methods defined in `instanceDefaults` get serialized into plain empty objects

~~According to the runkit included in this class methods should not be included.~~ Oh.. wait. I just updated it and if you have a property set to the value of a function (either by object notation `{someFn: () => "val"}` or with `Object.defineProperty(obj,"someFn",{enumerable: true, value: () => "val"})`) , but a class method is not copied.

https://github.com/feathers-plus/feathers-vuex/issues/196#issuecomment-466420458

So another piece to add to the documentation (https://github.com/feathers-plus/docs/issues/62) is that instanceDefaults shouldn't have enumerable functions, or they will be serialized to {}. 

Maybe it's better to add a check in the toJSON to not include functions? Probably with `_.mergeWith({},this,(objVal,srcVal) => (typeof srcVal === 'function') ? undefined : srcVal)`

**Comment by Palivonas** [comment]
FeathersVuex models (de)serialization into plain objects also cause problems when using Vuex time travel feature from Vue dev tools. Will look into possible locations for models' initialization when I'm done with some pressing projects.

**Comment by marshallswain** [comment]
@Palivonas @NickBolles in the latest pre-release, you have full access to each service's Model class, so you can override default JS methods to achieve what you want.  If you figure out a better default for `toJSON`, please let me know.

**Comment by marshallswain** [comment]
I looked into this issue more last night.  The only solution I can come up with is to create a client utility that runs immediately after the service is setup.  It needs to do the following:

1. Loop through the `list` getter.
2. Create an instance of each item in the list.
3. Replace the item in the store. (best to have a new mutation like `replaceItem` for this)

This would be very low cost as long as it is done before app initialization.  If it is done after the app has mounted, it would possibly cause a UI freeze or stutter from so many handlers running as the instances are replaced (depending on the amount of preloaded data).

**Comment by marshallswain** [comment]
I'm going to close this one in favor of https://github.com/feathers-plus/feathers-vuex/issues/265
