### ISSUE TITLE
Changelog is Outdated

### ISSUE THREAD

**Issue by Heartnett** [feathers-plus/feathers-vuex#200]
Hi, the changelog was last updated on Aug 26, 2017 for v1.0.0-pre.3 and the project is currently (at the time of writing) v1.7.0

**Comment by marshallswain** [comment]
I agree that this needs to be updated.  There's plenty of tagging in the [commits](https://github.com/feathers-plus/feathers-vuex/commits/master), so they read like a changelog until I make the time to update the actual changelog..

**Comment by marshallswain** [comment]
It's official.  I won't be going back to update the changelog.  The commits read just like a changelog.

**Comment by NickBolles** [comment]
@marshallswain maybe you could use conventional commits to enforce commit pattern and generate a changelog from commits? Just an idea, I've been using it on my current project and it's super nice.

**Comment by bravo-kernel** [comment]
@NickBolles a link to the topic would have been useful

- https://www.conventionalcommits.org
- http://notebook.aaronwest.net/2015/08/03/better-documentation-using-conventional-changelog.html
