### ISSUE TITLE
How to access this.$FeathersVuex in asyncdata?

### ISSUE THREAD

**Issue by smyth64** [feathers-plus/feathers-vuex#204]
Hi
It seems not possible to access the models in async data... Any idea?

**Comment by NickBolles** [comment]
I'm not super sure about this, but here are some ideas
I believe async data is run on the server. Are you initializing feathers vuex before or in nuxt server init? 

I think it should be on the context. If not it might be on the global Vue object too.

**Comment by Palivonas** [comment]
I do something like this in my `store/index.js`
```js
const { service, auth, FeathersVuex } = feathersVuex(feathersClient);
Vue.use(FeathersVuex);
export const Models = Vue.$FeathersVuex;
```
Then in components
```js
import { Models } from '~/store';
// ...
async asyncData() {
  const { data: posts } = await Models.Post.find();
  return { posts };
}
```

Or you could add a plugin like this:
```js
import { Models } from '~/store';

export default (context, inject) => {
  inject('models', Models);
};
```
And then in components
```js
async fetch({ app }) {
  await app.$models.Post.find();
}
```
( I prefer `fetch` and then computed getters, but `asyncData` also works )

**Comment by marshallswain** [comment]
In `feathers-vuex@2.x`, you can get access to the `$FeathersVuex` object by importing the `models` object from the main export:

```
import { models } from 'feathers-vuex'
```

`models` and `$FeathersVuex` are the same object.

**Comment by marshallswain** [comment]
Closing as I've added this to the preliminary docs
