### ISSUE TITLE
$and is not included in list of OPERATORS

### ISSUE THREAD

**Issue by jscottsf** [feathers-plus/feathers-vuex#222]
https://github.com/feathers-plus/feathers-vuex/blob/f56c00dde252349f8b856fe1cb5ba03c75b97369/src/service-module/getters.js#L9

Sift and MongoDB both support $and, which useful when referencing the same field multiple times in a query. Is there a workaround for this?

**Comment by J3m5** [comment]
The $and operator is implicit, it is simply specified by defining a value's property. See the [feathers doc](https://docs.feathersjs.com/api/databases/querying.html#equality).

**Comment by jscottsf** [comment]
There are cases in Mongo where the implicit "and" will not work. Hence, it is helpful to whitelist the "$and" operator. Whitelisting is a supported feature in Feathers. However, the pre-cleaning of operators breaks this functionality. Would it it possible skip this altogether and just let the commons filterQuery do all of the work as it does in the adapters?

AND Queries With Multiple Expressions Specifying the Same Operator
https://docs.mongodb.com/manual/reference/operator/query/and/

**Comment by marshallswain** [comment]
There are two places where the query operators have to be allowed.  

1. In the Feathers Client (for the actions)
2. Inside feathers-vuex (for the getters)

There's a `paramsForServer` option which configures feathers-vuex.  For the Feathers Client, just follow the crow docs.

**Comment by marshallswain** [comment]
Closing this as I've added it to the new preliminary docs.
