### ISSUE TITLE
instanceDefaults as an object can cause complications

### ISSUE THREAD

**Issue by james2mid** [feathers-plus/feathers-vuex#224]
**Neither a bug or a feature request**

I'm posting this for myself to come back to at a later time unless someone else wants to do it.

The issue is with instanceDefaults as an object where it maintains the contents of any array or object properties between model instances. The workaround for this is to make instanceDefaults a function that returns the same object.

It took me a little while to figure out why this was happening and so I felt this should be more clear in the docs, especially for the less versed coders out there.

**Comment by james2mid** [comment]
The code below will have `arr` maintain its value between instances when doing `new this.$FeathersVuex.Model()`.

```js
instanceDefaults: {
  arr: []
}
```

The workaround is to do this:
```js
instanceDefaults: () => ({
  arr: []
})
```

**Comment by marshallswain** [comment]
@james2mid thanks for making this more visible.  Version 2.x will only allow the function version.  I'm going to close this after it is released.

**Comment by james2mid** [comment]
See the PR above
