### ISSUE TITLE
Document and code are inconsistent for `service/create`

### ISSUE THREAD

**Issue by chengyuhui** [feathers-plus/feathers-vuex#230]
### Steps to reproduce
Pass an array of entities directly to `create` action

### Expected behavior
Based on [documentation](https://feathers-vuex.feathers-plus.com/service-module.html#service-actions), all the entities should be created.

### Actual behavior
Only the first entity in the array was created.

https://github.com/feathers-plus/feathers-vuex/blob/master/src/service-module/actions.js#L113 shows that create actually accepts a `paramArray` which looks like `[data, params]`, but this is not mentioned in docs.

**Comment by J3m5** [comment]
Did you set the "multi" setting to true or ["create"] on your service?
[It needs to be enabled to allow operation that handle multiple entries.](https://docs.feathersjs.com/api/databases/common.html#serviceoptions)

**Comment by chengyuhui** [comment]
@J3m5 The server configuration is correct. When I inspected the socket.io requests, it was clear that only the first item got sent.

**Comment by J3m5** [comment]
Ok, I have logged the data and params just before they are passed to the create method and it looks like if the data is an Array, it take the first item and use it as the data and take the second and use it as params. It's weird...
As you saild, to make it work you should pass your entries as [dataArray]

**Comment by chengyuhui** [comment]
Such behavior is consistent with `update`, `get`, and `patch`, which accept an array of arguments. This seems to be a simple documentation problem.

**Comment by marshallswain** [comment]
@chengyuhui Yep, this is a documentation mistake.  Thanks for opening this issue because I never would have caught it.

When an array is passed to the create method, it should behave exactly the same way as the update and patch methods.
