### ISSUE TITLE
diffOnPatch() clears all data for model instances

### ISSUE THREAD

**Issue by morphatic** [feathers-plus/feathers-vuex#237]
### Steps to reproduce

```js
// 1. instantiate a model instance and save it
const { Todo } = this.$FeathersVuex.myApi
const todo = new Todo({ item: 'Write tests', done: false }).save()

// 2. clone the instance and modify it
const clonedTodo = todo.clone()
clonedTodo.done = true

// 3. commit(?) and save the clone
clonedTodo.commit() // I've tried commenting this line out, and I get the same result either way
clonedTodo.save()

// 4. check result
if (todo.done) {
  console.log('Yay! Expected result.')
} else {
  console.log('Boo. Actual result.')
}
```

I did some digging and found that even though [`diffOnPatch()` in the v2.0.0-pre.62 codebase](https://github.com/feathers-plus/feathers-vuex/blob/v2.0.0-pre.62/src/service-module/make-model.ts#L57) is supposed to just return the submitted data by default, the built package has the following code (which appears to be a holdover from the previous version):

```js
// dist/service-module/service-module.actions.js#L169
      if (diffOnPatch) {
        var diff_1 = {}
        deep_diff_1.observableDiff(state.copy, data, function(d) {
          if (d.path && d.path.length) {
            // Apply all changes except to the id property...
            if (d.path[d.path.length - 1] !== idField) {
              deep_diff_1.applyChange(diff_1, data, d)
            }
          }
        })
        data = diff_1
      }
```

I threw a `console.log(data)` into the built module before and after the `if(diffOnPatch) {}` block and **before** the block it returned a `Todo` instance with my changes, but **after** the block, `data` had been converted to an empty object `{}` and therefore caused no changes in either the store or the API.

Any ideas what's happening?

- [x] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior

I'm expecting the changes to the model to get saved to the store **and** remote API.

### Actual behavior

Changes are not written to either the store or the API.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): v2.0.0-pre.62

**NodeJS version**: v10.15.3

**Operating System**: OSX 10.13.6 (High Sierra)

**Browser Version**: Chrome (mac) 75.0.3770.100

**Module Loader**: Vue v2.6.10, Vuex v3.1.1

**Comment by morphatic** [comment]
FYI, I thought there might be cruft in there from upgrading from a previous version, so I completely deleted `node_modules` and re-ran `npm i` making sure that `"feathers-vuex": "^2.0.0-pre.62"` was set correctly in `package.json`.

**Comment by marshallswain** [comment]
Something doesn't seem right, here.  The internal diffing has been pulled from `feathers-vuex`.  It has to be manually implemented in the class that extends `BaseModel`.

Could you actually open `/node_modules/feathers-vuex/package.json` and look at the version number?  I suspect that you have version `2.0.0` installed.  Try deleting the caret and installing again.

```
"feathers-vuex": "^2.0.0-pre.62" <-- will probably get you 2.0.0 from the `pre` tag.
"feathers-vuex": "2.0.0-pre.62" <-- will make sure you get the exact version
```

**Comment by morphatic** [comment]
🤦‍♂ #)(*%@#!@#!!!  thanks. that was it.
