### ISSUE TITLE
Suggestion: Better relationship

### ISSUE THREAD

**Issue by FedorSherbakov** [feathers-plus/feathers-vuex#245]
### Steps to reproduce
Consider some relationship between models:
```js
{
  plugins: [
    service('folders', {
      instanceDefaults: {
        parentFolder: 'Folder',
      },
    }),
    service('files', {
      instanceDefaults: {
        parentFolder: 'Folder',
      },
    }),
  ],
}
```

Relationship can be deeply nested like
`File -> Folder -> Folder -> Folder -> Folder -> etc.`

Finding a file:
```js
$FeathersVuex.File.find({
  query: {
    _id: 'blahblah',
    $populate: {
      path: 'parentFolder',
      populate: 'parentFolder',
    }
  }
})
```

### Actual behavior
Server will return the structure like:
```
[{
  _id: 'blahblah',
  parentFolder: {
    _id: 'folderID1',
    parentFolder: {
      _id: 'folderID2',
      parentFolder: 'folderID3',
    },
  },
}]
```

But FeathersVuex will parse every parentFolder field as the Folder model, even the 'folderID3' string, so the FeathersVuex will return like this:
```
[{
  _id: 'blahblah',
  parentFolder: {
    _id: 'folderID1',
    parentFolder: {
      _id: 'folderID2',
      parentFolder: {
        0: 'f',
        1: 'o',
        2: 'l',
        3: 'd',
        4: 'e',
        5: 'r',
        6: 'I',
        7: 'D',
        8: '2',
        9: 'f',
      },
    },
  },
}]
```

### Expected behavior
FeathersVuex won't parse fields, which intended to be an object, but actually they are not (because they store only the id currently)
It could remember about this missing relationship and replace id string with the object when it's fetched in the future

### System configuration

Mongo DB
Mongoose
feathers-vuex 1.7.0

**Comment by marshallswain** [comment]
Thanks for the feedback @FedorSherbakov.  I completely agree that this was a design flaw from the beginning.  It has already been fixed in the latest pre-release.  I recommend using the latest pre-release.  Instructions are in the PR for the huge update, which will be released soon with V4 authentication plugin support.
