### ISSUE TITLE
SyntaxError Unexpected identifier

### ISSUE THREAD

**Issue by twobitunicorn** [feathers-plus/feathers-vuex#256]
### Steps to reproduce
Create a Nuxt app, add feathers-vuex @pre (and associated dependencies), throw in a feathers client.  Now ```import feathersVuex from 'feathers-vuex'``` and startup the server.  You should see an error of ```SyntaxError Unexpected identifier```

Here is the output from .nuxt/store

      updateModules()
      // Trigger a hot update in the store.
      window.$nuxt.$store.hotUpdate(store)
    })
  }
})()

with the last line highlighted. 

Example repo:
https://github.com/twobitunicorn/feathers-vuex-example

**Comment by twobitunicorn** [comment]
Doing a `nuxt build`, `nuxt run` I get this as an error.
``` ERROR  Unexpected identifier                                                                                                                                                                                                                                                                                                                                     14:04:11

  import setupAuthModule from './auth-module/auth-module'
  ^^^^^^^^^^^^^^^

  SyntaxError: Unexpected identifier
  at new Script (vm.js:86:7)
  at createScript (vm.js:268:10)
  at Object.runInThisContext (vm.js:316:10)
  at Module._compile (internal/modules/cjs/loader.js:860:26)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
  at Module.load (internal/modules/cjs/loader.js:790:32)
  at Function.Module._load (internal/modules/cjs/loader.js:703:12)
  at Module.require (internal/modules/cjs/loader.js:830:19)
  at require (internal/modules/cjs/helpers.js:68:18)
  at node_modules/vue-server-renderer/build.prod.js:1:77688
```

**Comment by marshallswain** [comment]
@twobitunicorn This is a nuxt configuration issue. By default with Nuxt, the build server doesn't understand the word `import`, which is ES6 module syntax.  You have to tell Nuxt in the config which node_modules to transpile from ES6 to ES5.  (I tried avoiding this situation, but double transpilation while implementing classes can cause major issues at deployment time.) . Thankfully, the fix is easy in nuxt.config.js:

```js
build: {
    transpile: ['feathers-vuex'],
}
```

**Comment by twobitunicorn** [comment]
@marshallswain Rad, thanks!

**Comment by twobitunicorn** [comment]
@marshallswain In the interm I switched over to using Vue CLI.  The issue is exactly the same.  I added `transpileDependencies: ['feathers-vuex']` to `vue.config.js` and still having the same issue.  Where would this fit into the Vue CLI eco system?

**Comment by marshallswain** [comment]
Read the comments here for possible solutions:

https://github.com/feathers-plus/feathers-vuex/pull/216

**Comment by marshallswain** [comment]
Please leave this open.  It's my reminder to update the docs.

**Comment by twobitunicorn** [comment]
Will do. Thanks again!

**Comment by marshallswain** [comment]
Closing as I've added this to the preliminary docs.
