### ISSUE TITLE
Cannot read property '_' of undefined -> getters.js

### ISSUE THREAD

**Issue by ivanninet** [feathers-plus/feathers-vuex#259]
### Steps to reproduce

npx @vue/cli create new-app
cd new-app
npm run serve --> works
...
npm i -s feathers-vuex

store.js file
import feathersVuex from 'feathers-vuex'

app stop working

![issue-feathers-vuex](https://user-images.githubusercontent.com/43170623/64344741-59aaa600-cfef-11e9-98ed-388a6d270093.png)
![issue-feathers-vuex2](https://user-images.githubusercontent.com/43170623/64344743-59aaa600-cfef-11e9-838a-83b92aa5990a.png)

### Expected behavior

Expected to be able to import feathers-vuex

### Actual behavior
App breaks

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

  "dependencies": {
    "core-js": "^2.6.5",
    "feathers-vuex": "^1.7.0",
    "vue": "^2.6.10",
    "vue-router": "^3.0.3",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.11.0",
    "@vue/cli-plugin-eslint": "^3.11.0",
    "@vue/cli-service": "^3.11.0",
    "@vue/eslint-config-prettier": "^5.0.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.16.0",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-vue": "^5.0.0",
    "prettier": "^1.18.2",
    "vue-template-compiler": "^2.6.10"
  },

**NodeJS version**:
v11.15.0
**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by marshallswain** [comment]
https://github.com/feathers-plus/feathers-vuex/issues/248

**Comment by marshallswain** [comment]
Make sure you have the latest version installed.  There should be no caret character in the package.json version number.  

```
"feathers-vuex": "2.0.0-pre.75",
```

NOT THIS:
```
"feathers-vuex": "^2.0.0-pre.75",
```
