### ISSUE TITLE
Using listStrategy: 'Always'

### ISSUE THREAD

**Issue by Vensla** [feathers-plus/feathers-vuex#260]
I am porting an angular app to vue and I have trouble figuring out where I should set the listStrategy params. Tried adding it before the query but it still doesn't work I don't get updates when orders change. Any suggestions?

Angular code:
```    
this.ordersObservable$ = this.feathers.watch('orders', { listStrategy: 'always'})
.find({ query: {...
```
Vue code: 
```
this.findOrders({
  listStrategy: 'always',
  query: {
```

**Comment by marshallswain** [comment]
Feathers-Vuex doesn't use the rxjs plugin and instead taps into Vue's "native" reactivity system.  While `listStrategy` technically doesn't apply here, you can get the equivalence of `listStrategy: 'always'` by using the `find` getter.  Any time the data updates, the list of results will auto-update, as well.
