### ISSUE TITLE
feathersClient.passport is undefined

### ISSUE THREAD

**Issue by johnackley** [feathers-plus/feathers-vuex#264]
Perhaps passport is no longer available in feathersClient?
Or instructions for initializing it are missing?

### Steps to reproduce

Followed the feathers-vuex v2 setup instructions, talking to vanilla feathers4 server.
dispatch('auth/authentication', creds) succeeds, but fails in the responseHandler().

The promise chain in auth-modules.actions.ts:makeAuthActions():responseHandler() breaks because feathersClient.passport is undefined:

responseHandler({ commit, state, dispatch }, response) {
      if (response.accessToken) {
        commit('setAccessToken', response.accessToken)

        // Decode the token and set the payload, but return the response
        return feathersClient.passport // <<<<<<<<<
          .verifyJWT(response.accessToken)
          .then(payload => {
            commit('setPayload', payload)

### Expected behavior
Tell us what should happen

### Actual behavior
mutation auth/unsetAuthenticatePending @ 06:31:28.390
Signin.vue?3d55:43 TypeError: Cannot read property 'verifyJWT' of undefined
    at Store.responseHandler (auth-module.actions.js?60a7:31)
    at Array.wrappedActionHandler (vuex.esm.js?2f62:732)
    at Store.dispatch (vuex.esm.js?2f62:437)
    at Store.boundDispatch [as dispatch] (vuex.esm.js?2f62:331)
    at local.dispatch (vuex.esm.js?2f62:662)
    at eval (auth-module.actions.js?60a7:18)

### System configuration
Client:
    "@feathersjs/authentication-client": "^4.3.1",
    "@feathersjs/client": "^4.3.1",
    "@feathersjs/rest-client": "^4.3.1",
    "@feathersjs/socketio-client": "^4.3.1",
    "@quasar/extras": "^1.3.1",
    "feathers-vuex": "^2.0.0-pre.77",
    "quasar": "^1.1.0",
    "socket.io-client": "^2.2.0",
Server:
    "@feathersjs/authentication": "^4.3.1",
    "@feathersjs/authentication-local": "^4.3.1",
    "@feathersjs/authentication-oauth": "^4.3.1",
    "@feathersjs/configuration": "^4.3.1",
    "@feathersjs/errors": "^4.3.1",
    "@feathersjs/express": "^4.3.1",
    "@feathersjs/feathers": "^4.3.1",
    "@feathersjs/socketio": "^4.3.1",

**Module versions** (especially the part that's not working):

**NodeJS version**:
v10.16.0

**Operating System**:
Darwin Liberty.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Browser Version**:
Google Chrome is up to date
Version 77.0.3865.75 (Official Build) (64-bit)

**React Native Version**:

**Module Loader**:
web pack (via Quasar.dev)

**Comment by johnackley** [comment]
missed that this was related:
https://github.com/feathers-plus/feathers-vuex/issues/235#issuecomment-513953268
Following this approach until v2 released.

**Comment by marshallswain** [comment]
Support for Feathers v4 auth is now baked into `feathers-vuex@2.0.0-pre.78`.
