### ISSUE TITLE
Tests not working on NPM 12 (testee outdated)

### ISSUE THREAD

**Issue by rayfoss** [feathers-plus/feathers-vuex#267]
Testee has been updated to support it... and not depend on the condemned natives package.

please update to "testee": "^0.9.1"... 

This test fails for me, `converts keys that contain the Date constructor into date instances:` that sounds like a bad idea anyway... I hate date objects unless I need them

and this 
```
setCurrent works on model instances with getters:
     setCurrent preserved the getter accessor prop
```

## Update
> Setting the current item or id also create the deep-cloned copy.

That's just not happening for some reason, hence the test fails.

## Update
The copy setCurrent makes is really bad
``` 
// Real object:
{
    firstName: 'Al',
    lastName: 'fred',
    location: { coordinates: [Array] },
    fullName: 'Al fred',
    id: 1
  }
// Set current copy:
  {
    ids: [ 1 ],
    keyedById: { '1': [Object] },
    copiesById: {},
    currentId: 1,
    copy: {
      firstName: '',
      lastName: '',
      location: [Object],
      fullName: ' ',
      id: 1
    }
```

**Comment by marshallswain** [comment]
> This test fails for me, converts keys that contain the Date constructor into date instances: that sounds like a bad idea anyway... I hate date objects unless I need them

I totally agree.  This is one of the reasons the API for handling relationships was overhauled in v2.x.

**Comment by rayfoss** [comment]
i couldn't fix it... closing. This branch is about to be steam rolled anyway
