### ISSUE TITLE
 "Uncaught TypeError: service is not a function"

### ISSUE THREAD

**Issue by HarisHashim** [feathers-plus/feathers-vuex#272]
I am trying to use latest FeathersJS (4.3.2) with prerelease Feathers-Vuex 2.0.0-pre.75 (solution to issue #247).

I am getting error as pictured. 
"Uncaught TypeError: service is not a function"

Question: feathers-vuex newer version no longer returning service as function? Maybe documentation/tutorial how to use Feathers-Vuex need to change?

My vuex store index.js code as in picture and my feathersClient follow tutorial 

https://feathers-vuex.feathers-plus.com/api-overview.html#features

``
import feathers from "@feathersjs/feathers";
import socketio from "@feathersjs/socketio-client";
import auth from "@feathersjs/authentication-client";
import io from "socket.io-client";

const socket = io("http://localhost:3030", { transports: ["websocket"] });

const feathersClient = feathers()
  .configure(socketio(socket))
  .configure(auth({ storage: window.localStorage }));

export default feathersClient;``

![image](https://user-images.githubusercontent.com/1856131/65374717-8503e500-dcbf-11e9-94b0-6060c1f01ad2.png)

**Comment by apmcodes** [comment]
Getting the same error with Feathers-Vuex 2.0.0-pre.77.

**Comment by apmcodes** [comment]
Going through the [2.x update](https://github.com/feathers-plus/feathers-vuex/pull/216)

**Comment by J3m5** [comment]
The way the services are added in 2.x has changed, you should look at https://github.com/feathers-plus/feathers-vuex/pull/216 and follow the instructions.

**Comment by apmcodes** [comment]
OMG! After spending few hours scratching head got the upgrade to 2.x working. Phew!!!

@J3m5 Yes followed #216 and then encountered #238.

For Quasar app transpileDependencies can be updated in **quasar.conf.js** under **build** as

`transpileDependencies: ['feathers-vuex'],`

**Comment by marshallswain** [comment]
I'm sorry that the Feathers release has caused some extra time spent on the upgrade.  It has not been possible for me to manage all of my other responsibilities along with keeping ahead of the recent changes.  This is a rare thing, but I appreciate your patience.  I've added a note to the Readme.  I'm going to close this.

**Comment by apmcodes** [comment]
@marshallswain Thank you very much for such a useful library and your continued effort.
