### ISSUE TITLE
Repeated strange console messages ... seems after upgrade to 2.x

### ISSUE THREAD

**Issue by apmcodes** [feathers-plus/feathers-vuex#277]
Noticed these console messages recently after upgrade to 2.x. The message repeats every few seconds. Have no idea what can this be. Can someone please let me know. 

```
assigning temporary id to item 
Job {}
__id: (...)
__isTemp: (...)
__ob__: Observer {value: Job, dep: Dep, vmCount: 0}
get __id: ƒ reactiveGetter()
set __id: ƒ reactiveSetter(newVal)
get __isTemp: ƒ reactiveGetter()
set __isTemp: ƒ reactiveSetter(newVal)
__proto__: BaseModel
```
![Screenshot from 2019-09-28 00-13-11](https://user-images.githubusercontent.com/13360356/65794068-f393e780-e184-11e9-892a-9b9211976286.png)

Job is a vue store. 

```
class Job extends BaseModel {
    // required
    constructor(data, options) {
        super(data, options)
    }
    // required
    static modelName = 'Job'
}

const jobPlugin = makeServicePlugin({
    Model: Job,
    service: client.service('job'),
    enableEvents: true,
    idField: 'id'
})
```

**Comment by apmcodes** [comment]
The message appears just after a Create method call, which receives a response with the id.

![Screenshot from 2019-09-28 00-20-59](https://user-images.githubusercontent.com/13360356/65794494-e4fa0000-e185-11e9-8ee0-bc35125638cd.png)

**Comment by marshallswain** [comment]
@apmcodes It seems that my `getId` util, [found here](https://github.com/feathers-plus/feathers-vuex/blob/typescript/src/utils.ts#L183), needs some work.  What your issue means is that the `getId` method, as it is currently written, is unable to find an `id` in you records.  I suspect that we need a better check than `.hasOwnProperty`.

The message you're getting comes from executing this line: https://github.com/feathers-plus/feathers-vuex/blob/typescript/src/service-module/service-module.mutations.ts#L45.  It basically means that the majority of the feathers-vuex modeling functionality will not work for you until we fix this issue.

I suspect that we could probably fix this issue by updating the `getId` utility to do two checks:

```js
/**
 * Get the id from a record in this order:
 *   1. id
 *   2. _id
 *   3. the `idField`
 * @param item
 */
export function getId(item, idField) {
  if (!item) {
    return
  }
  if (item.id != null || item.hasOwnProperty('id')) {
    return item.id
  }
  if (item._id != null || item.hasOwnProperty('_id')) {
    return item._id
  }
  if (item[idField] != null || item.hasOwnProperty(idField)) {
    return item[idField]
  }
}
```

Could you try opening the `utils.js` file in your `node_modules/feathers-vuex` folder and modifying the util with those changes?  I suspect it will.  If it does, I'll ship a fix ASAP.

**Comment by marshallswain** [comment]
Fixed in https://github.com/feathers-plus/feathers-vuex/commit/101a7d3cf6c4b22b486ca8e27eae129d14f7c64e
