### ISSUE TITLE
Cannot read property 'api' of undefined => Feathers-vuex@2.0.0-pre.78 / Quasar

### ISSUE THREAD

**Issue by GuillaumeFERNANDESXP** [feathers-plus/feathers-vuex#279]
Hi, I have a problem with this latest version. I'm making a project on Quasar + Feathers4 + mongodb.
In my webconsole: 
"[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'api' of undefined"

In my Index.vue

methods: {
    signUp () {
      if (this.valid) {
        const { User } = this.$FeathersVuex.api
        const user = new User(this.user)
        user.save()
          .then(user => {
            console.log(user)
            this.$router.push('./login')
          })
      }
    }
  }

In my feathers-client.js

import feathers from '@feathersjs/feathers'
import socketio from '@feathersjs/socketio-client'
import authClient from '@feathersjs/authentication-client'
import io from 'socket.io-client'
import feathersVuex from 'feathers-vuex' // or '@/libs/feathers-vuex' if you're copying feathers-vuex as mentioned earlier.

// Setup the Feathers client
const host = 'http://localhost:3030'
const socket = io(host, { transports: ['websocket'] })
const feathersClient = feathers()
  .configure(socketio(socket))
  .configure(authClient({ storage: window.localStorage }))

export default feathersClient

// Setup feathers-vuex
const {
  makeServicePlugin,
  makeAuthPlugin,
  BaseModel,
  models,
  clients,
  FeathersVuex
} = feathersVuex(feathersClient, {
  serverAlias: 'myApi', // or whatever that makes sense for your project
  idField: '_id' // `id` and `_id` are both supported, so this is only necessary if you're using something else.
})

export {
  makeAuthPlugin,
  makeServicePlugin,
  BaseModel,
  models,
  clients,
  FeathersVuex
}

Do you have any idea of what's making this error? Maybe ServerAlias ?
Thanks

**Comment by marshallswain** [comment]
Two things:

1. You're missing `Vue.use(FeathersVuex)`
2. You've set the serverAlias to `myApi`, so you need to do `const { User } = this.$FeathersVuex.myApi` to find the model (after you register the plugin)

**Comment by GuillaumeFERNANDESXP** [comment]
Thanks @marshallswain
