### ISSUE TITLE
does FV have default listeners for create/update/patch events?

### ISSUE THREAD

**Issue by dkebler** [feathers-plus/feathers-vuex#281]
I just assumed (based on looking at the chat example) that FV has some essential (client) listeners baked in.  I mean if feathers backend emits  the same after created/update/patch actions (which I see it doing) then I kinda assumed that any frontend instance connected would see its FV store for that document updated via a get (and thus react).  I do NOT see any listeners set in the example chat app which made me figure it was baked in.

If that is true then I seem to have a bug since I see backendlogs like this 
`Publishing all events to all authenticated users. See `channels.js` and https://docs.feathersjs.com/api/channels.html for more information.
`    (wondering if somehow my FV enabled client is not listening) but an alternate open browser instance is not updating its reactive document properties.

If these listeners where not baked in then I guess I have set my own listeners for those events and dispatch my own gets, although IMO this should be the default, or at least turned on via an option.

**Comment by marshallswain** [comment]
They are baked in, here: https://github.com/feathers-plus/feathers-vuex/blob/typescript/src/service-module/make-service-plugin.ts#L93

**Comment by dkebler** [comment]
ok, should have looked here, just as I said an option. :-)
https://feathers-vuex.feathers-plus.com/service-module.html#service-state

But according to that the default is true, yes?  So should be working by default.

So I have a bug or maybe feathers4 (which I am using both ends) is blocking the event.  I currently have no authentication required on the backend to access the socket so maybe that's it?? cause they have new authentication, channels etc.

**Comment by dkebler** [comment]
Also in the handler for some of those events I see  dispatch addOrUpdate.  

```javascript
        service.on('updated', item =>
          store.dispatch(`${options.namespace}/addOrUpdate`, item)
        )
```


dispatch seems a bit weird.  I can't find addOrUpdate in the api docs https://feathers-vuex.feathers-plus.com/service-module.html#service-state  but I assume it doesn't actually disptach anything to backend (since that is where update came from) and just ends up committing the changes locally?

**Comment by dkebler** [comment]
Yup it was the new channels on the backend.

I had to add this to my backend app

```javascript
// send all events to everyone
  app.publish((data, context) => {  // eslint-disable-line no-unused-vars
    return app.channel('anonymous')
  })
// add all incoming users to anonymous channel
  app.on('connection', con => {
    console.log('incoming connection', con)
    app.channel('anonymous').join(con)
  })
```

apparently there are no "channels" on the client.  At least I don't see such in the doc and the events sent on the anonymous channel is received by the client without a change to your code.  Not that this is a FV issue but in the 2.0 docs you might make mention of this for those using 4.0.  Otherwise folks will think it's FV.

@marshallswain you can close this if you have no other replies

**Comment by marshallswain** [comment]
I'll leave this open as a reminder to add it to the docs.  

Regarding your comment from earlier:

>dispatch seems a bit weird. I can't find addOrUpdate in the api docs https://feathers-vuex.feathers-plus.com/service-module.html#service-state but I assume it doesn't actually disptach anything to backend (since that is where update came from) and just ends up committing the changes locally?

Since you can't call a Vuex mutation from another mutation, I had to dispatch an action that determines which mutation to use, based on whether or not the item is already in the store.
