### ISSUE TITLE
Demo Page is throwing security errors

### ISSUE THREAD

**Issue by adavie1** [feathers-plus/feathers-vuex#298]
### Steps to reproduce
Click on the [Demo](https://codesandbox.io/s/xk52mqm7o) link.

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [X] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
A working Demo ;-)

Tell us what should happen

### Actual behavior
A lot of errors, during transpiling, then a Security error:
![Selection_497](https://user-images.githubusercontent.com/3030402/66615758-8a8a8600-ec00-11e9-97f4-51fba38ca9e5.png)

### System configuration

Tell us about the applicable parts of your setup.

**N/A** - this is off the `github readme.md`

**Comment by marshallswain** [comment]
What do I need to do to get it to break?  I tested with latest Chrome stable and it compiled right away without error.

<img width="2558" alt="Screen Shot 2019-10-15 at 2 10 13 AM" src="https://user-images.githubusercontent.com/128857/66812924-06cae500-eef1-11e9-99e5-bf21f69dfa9c.png">

**Comment by marshallswain** [comment]
I'm closing this since I'm not able to reproduce the error.
