### ISSUE TITLE
Please put potential build issues here

### ISSUE THREAD

**Issue by marshallswain** [feathers-plus/feathers-vuex#304]
If you run into issues with the build for `feathers-vuex@2.x`, please comment in this issue.  So far, I've been able to work around issues by copying feathers-vuex into the `src` folder of my Vue projects.  If you find an issue you can't seem to resolve, this is the recommended solution until we've documented the possible options.

You can look at previous conversation about the topic on the PR: #216

**Comment by corepay** [comment]
:) nice surprise to open the docs and see the updates this morning!

Documentation issue or bug: 

Not sure which but following along upgrading pre22 -> looks like you added feathers-hooks-common and imported `iff` but I think you also need to import `discard` - I ma getting linter error, comment out then build to blank page.  Adding `discard` to the import everything seems to be good again but I dont know up from down re: feathers-hooks-common

![image](https://user-images.githubusercontent.com/48992923/67229545-854fe700-f409-11e9-9f03-b655d9f0aa6a.png)

**Comment by marshallswain** [comment]
@corepay thanks!  fixed

**Comment by ikakosta** [comment]
Hi, @marshallswain nice work.

I have upgraded my app to the latest feathers vuex but `current` getter is missing? If this getter is removed, [docs](https://feathers-vuex.feathers-plus.com/service-plugin.html#service-getters) need to be fixed.

**Comment by marshallswain** [comment]
@ikakosta thanks for bringing this to my attention.  I will update the docs.  

https://feathers-vuex.feathers-plus.com/2.0-major-release.html#the-currentitem-workflow-is-no-longer-supported

**Comment by marshallswain** [comment]
@ikakosta docs are updated.  Please have a look in about 5 minutes.
