### ISSUE TITLE
how to set Each service module individually configured option?

### ISSUE THREAD

**Issue by fionagithub** [feathers-plus/feathers-vuex#44]
when i used this,i need to set some diff option,and i've no idea ,plz help

**Comment by marshallswain** [comment]
@fionagithub I missed your message until just now.  If you switch to the 1.0 branch, you'll be able to customize the vuex modules quite easily.  Check out https://github.com/feathers-plus/feathers-vuex/issues/40 for more info.

**Comment by marshallswain** [comment]
Version 1.x has shipped!  `npm install feathers-vuex@latest`  It's very easy to customize, now.  See the docs in the Readme.md.

**Comment by fionagithub** [comment]
great！i saw it in readme.md.i can easy to set  specify custom options per service.thx!
