### ISSUE TITLE
Nuxt does not know window.localStorage

### ISSUE THREAD

**Issue by CalvinWalzel** [feathers-plus/feathers-vuex#50]
I just wanted to give feathersjs a try in combination with VueJS/Nuxt and feathers-vuex, but the docs seem to leave one small detail out that makes my whole application not work: When I add feathers-vuex (version 1.0.0-pre3) and I add `.configure(auth({ storage: window.localStorage }))` inside feathers-client.js, Nuxt complains that window is not defined due to it running both client and server side.

**Comment by kharhys** [comment]
To ensure that client side code is not run on the server, declare it in a `plugin` and then configure `nuxt` to disable `ssr` for the `plugin` i.e add `{ src: '~/plugins/feathers', ssr: false }` to nuxt plugins config if you defined your feathers client in `~plugins/feathers.js`. 

Mine looks like this
```
import Vue from 'vue'
import feathersVuex from 'feathers-vuex'
import feathersClient from '~api/feathers'

export default function ({app, store}) {
    feathersClient.configure(feathersVuex(store, { idField: '_id', uth: { userService: '/users' } }))
    feathersClient.service('subscribers')
    feathersClient.service('users')
    console.log(feathersPlugin)
    app.api = feathersClient
    window.store = store // window is always defined
    const feathersPlugin = {
      install (Vue, options) {
        Vue.mixin({
          created: function () {
            // access feathersClient on any component
            this.$api = feathersClient
          }
        })
      }
    }
    Vue.use(feathersPlugin)
}

```

I have defined feathersClient in a separate file `~api/feathers.js`. In this file I check`process.browser` environment variable available in nuxt before initializing feathers. This way, you are sure feathersClient will only be available on the client.
```
//import * as axios from 'axios'
import feathers from 'feathers'
import io from 'socket.io-client'
import hooks from 'feathers-hooks'
import reactive from 'feathers-reactive'
import socketio from 'feathers-socketio'
import auth from 'feathers-authentication-client'

const init = () => {
    const host = process.env.HOST || '127.0.0.1'
    const port = process.env.PORT || '3030'
    const socket = io(`http://${host}:${port}`)
    const endpoint = `http://${host}:${port}`
    const storage = require('localforage')

    const feathersClient = feathers()
        .configure(hooks())
    //    .configure(socketio(socket, isServer, rest(endpoint).axios(axios)))
        .configure(socketio(socket))
        .configure(auth({storage}))
        .configure(reactive({idField: '_id'}))


    socket.on('connect', () => { console.log('nuxt socket.io connected') })
    socket.on('event', (data) => { console.log('nuxt socket.io event',data) })
    socket.on('disconnect', (data) => { console.log('nuxt socket.io disconnect',data) })
    socket.on('reconnect', (data) => { console.log('nuxt socket.io reconnect',data) })

    window.feathers = feathersClient // this wont throw even with ssr

    return feathersClient
}

export default process.browser ? init() : () => console.error('feathersClient is not available on SSR client')

```

**Comment by marshallswain** [comment]
@CalvinWalzel to get this to work with Server-Side Rendering, you can actually swap out the storage provider in the `feathers-authentication-client` configuration to use the [cookie-storage](https://www.npmjs.com/package/cookie-storage) adapter.  Putting the JWT in a cookie will allow it to reach the server.  

You can then follow the section in the guide about using `feathers-vuex` with nuxt: https://github.com/feathers-plus/feathers-vuex/tree/1.0#working-with-auth--nuxt

**Comment by CalvinWalzel** [comment]
Thank you!
