### ISSUE TITLE
errorOn state set to empty object by action error handlers

### ISSUE THREAD

**Issue by cronik** [feathers-plus/feathers-vuex#58]
### Steps to reproduce

Execute an action on the store that results in a rejected promise from the feathers service.

The action error handlers use `Objects.assign({}, error)` to construct the mutation payload which results in an empty object. You can see this in action here, https://runkit.com/embed/4dduppvm6ldg

The mutation methods call `serializeError(payload)` which seems to indicate that is expecting an error type, so the `Objects.assign` can probably be removed.

### Expected behavior
Expect `errorOn*` state (i.e. `errorOnFind`) to have a non-empty Object with properties from the error.

```javascript
errorOnFind: {
  message: 'an error happened'
}
```

### Actual behavior
An empty object is assigned
```javascript
errorOnFind: {}
```
### System configuration

**Module versions** (especially the part that's not working):
feathers-vuex: 1.0.3

**Operating System**:
macOS Sierra

**Browser Version**: 
Chrome 61

**Comment by marshallswain** [comment]
@cronik this makes sense to me.  Do you want to take a crack at a PR that handles the error correctly?

**Comment by marshallswain** [comment]
Also, thank you for reporting this.

**Comment by cronik** [comment]
@marshallswain sure, I will attempt to put together a PR for this issue
