### ISSUE TITLE
wait for find in combination with feathers-reactive

### ISSUE THREAD

**Issue by LowM4N** [feathers-plus/feathers-vuex#59]
How can I wait for a find action in combination with feathers-reactive?

I have a nuxt application with server side rendering. If i am using feathers-vuex without feathers-reative, I get the expected behaviour, my asyncData function wait for the find and the data is in my store.

With feathers-reactive i have the problem that I dont know when the find finish, because the obseverable get subscribed in the find action ([see here](https://github.com/feathers-plus/feathers-vuex/blob/6a23c35d1110b38456a7d18cf853b93d3a6330a6/src/service-module/actions.js#L33)), which returns only a subscription, that i can only unsubscribe.

How I can handle this?
Maybe it's better to return the observable and the subscription from find, that i can handle this with another subscription?

My current solution is a bit hacky, I'm waiting 100-1000ms with setTimeout...

```
...
const PROJECTS_PER_PAGE = 12
const getPage = (page, store) => store.dispatch('projects/find', {
  qid: 'projects-page',
  query: {
    $limit: PROJECTS_PER_PAGE,
    $skip: ((page ? parseInt(page) : 1) - 1) * PROJECTS_PER_PAGE,
    $sort: {
      createdAt: -1
    }
  }
})
...
```
```
...
  async asyncData (ctx) {
    const { route, store } = ctx
    const { query } = route
    let page = parseInt(query.page)

    if (!page || page < 1) {
      page = 1
    }

    await getPage(page, store)

    return {
      page
    }
  }
...
```

```
// DIRTY APPROACH
  async asyncData (ctx) {
    const { route, store } = ctx
    const { query } = route
    let page = parseInt(query.page)

    if (!page || page < 1) {
      page = 1
    }

    return new Promise(async (resolve, reject) => {
      try {
        await getPage(page, store)
      } catch (err) {
        defaultExceptionHandler(err)
      }

      if (isServer) {
        setTimeout(() => resolve({
          page
        }), 1000)
      } else {
        resolve({
          page
        })
      }
    })
  }
```

**Comment by marshallswain** [comment]
Hmm.. I've never tried to use feathers-reactive with SSR.  I'm curious, why do you want feathers-reactive?  The latest version automatically subscribes to the realtime events, which was the main feature that feathers-reactive was bringing to the table, before.

**Comment by LowM4N** [comment]
Now I don't need feathers-reactive any more and all works as expected.

I used it before like that:
```
  async asyncData (ctx) {
    const { route, isServer, store } = ctx
    const { query } = route
    let page = parseInt(query.page)

    if (!page || page < 1) {
      page = 1
    }

    return new Promise(async (resolve, reject) => {
      try {
        await await getPage(page, store)
      } catch (err) {
        defaultExceptionHandler(err)
      }

      // TODO DIRTY NEED A BETTER SOLUTION
      if (isServer) {
        setTimeout(() => resolve({
          page
        }), 500)
      } else {
        resolve({
          page
        })
      }
    })
  },
  computed: {
    ...mapGetters('posts', {
      getPostFromStore: 'get'
    }),
    ...mapState('posts', {
      pagination: state => state.pagination['blog-page']
        ? state.pagination['blog-page']
        : null
    }),
    posts () {
      const { getPostFromStore, pagination } = this

      if (pagination) {
        return pagination
          .ids
          .map(id => getPostFromStore(id))
      }

      return []
    }
  },
```

but like that, the data doesn't get updated, when I'm creating new items. Now I'm using the find getter with the same query, like in the action and all works like a charm :)

**Comment by marshallswain** [comment]
Ok.  Beautiful.  That is how I intended the new version to be used.  Thank you for the update!

**Comment by daenuprobst** [comment]
There should be a nice example (maybe an implementation of a blog engine) that shows stuff like this. The chat example that's available on github is just too basic.
