### ISSUE TITLE
wrong import

### ISSUE THREAD

**Issue by nueko** [feathers-plus/feathers-vuex#62]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [x] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
it should import the proxied file on lib/client/index

### Actual behavior
not import the correct file
```js
// quick solution for that is
import feathersClient from 'feathers/lib/client'
```

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (latest):

**NodeJS version**: 6.11.4

**Operating System**: Windows 10

**Browser Version**: Chrome 61.0.3163.100 (Official Build) (64-bit)

**React Native Version**:

**Module Loader**: webpack

**Comment by marshallswain** [comment]
Thanks!  What was the import that was breaking?

**Comment by nueko** [comment]
sorry missing that.
```js
// currently incorect
import feathersClient from 'feathers/client'
// corect
import feathersClient from 'feathers/lib/client'
```

**Comment by marshallswain** [comment]
Since the latest Feathers release, the proper import is now for `@feathersjs/client`

https://www.npmjs.com/package/@feathersjs/client
