### ISSUE TITLE
[Feature] implement $search or $like query

### ISSUE THREAD

**Issue by nueko** [feathers-plus/feathers-vuex#63]
Halo,
that'll be great if we can use $search or $like query to the getters find.

Thanks.

**Comment by maximeLong** [comment]
+1 this feature, but also supporting $populate. The better fix would be to add a parameter on the module for supporting additional queries on socket event updates.

**Comment by marshallswain** [comment]
It feels like having hooks on getters would be a good thing.  We've have to figure out how to make it happen on the technical level.

**Comment by nueko** [comment]
@maximeLong, the `$populate` is working, tried last month with my last project.

**Comment by nueko** [comment]
@marshallswain, yes, I think $search feature on getters service would be enough.

**Comment by maximeLong** [comment]
@nueko $populate works on initial query but doesn't run on the getter update.

**Comment by alidplus** [comment]
its very useful for get search results and using packages like [feathers-mongodb-fuzzy-search](https://github.com/arve0/feathers-mongodb-fuzzy-search)

**Comment by marshallswain** [comment]
The latest update provides a way to accomplish this using the API available in the sift package, here: https://www.npmjs.com/package/sift

**Comment by apmcodes** [comment]
Is there a way to use `$like` in feathers-vuex (api server uses feathers-sequelize)?

**Comment by walkerandco** [comment]
One thing I should point out is that there isn't anything referencing the more advanced querying sift provides in the documentation. I have checked over all of the documentation and you reference only the Query API and Database API within feathers itself. There is nothing to explain the further functionality from sift you reference above.

**Comment by J3m5** [comment]
You can use the $regex operator in your computed queries as it is available in t[he sift package](https://github.com/crcn/sift.js#regex).
