### ISSUE TITLE
Support compound idFields

### ISSUE THREAD

**Issue by x42y** [feathers-plus/feathers-vuex#67]
I'm getting the same error as #61 , but I'm not sure if it's for the same reason?

I have a postgres database, using sequelize in the backend, and obviously feathers-vuex in the frontend :)

In other tables, I am using a single key (id) for PK, but in the table below I have a composite PK. Here is the SQL:
`CONSTRAINT u_translations_pk PRIMARY KEY (project_id, key_id, project_language_id, version),`

Adding a new value to the database is done in this method:
```
updateTranslation(keyId, langId, newValue){
      let data = {text: newValue}
      let params = {}

      this.findTranslation({
        query: {
          project_id: this.projectId,
          key_id: keyId,
          project_language_id: langId,
          version: 1
        }
      })
      .then(result => {
        if(result.total === 1){
          //this.patchTranslation([])
        }else if(result.total === 0){
          console.log('this.projectId: ', this.projectId)
          this.createTranslation({ project_id: this.projectId, key_id: keyId, project_language_id: langId, version: 1, text: newValue })
          .then(result => {
            console.log('success!')
            console.log('createTranslation result: ', result)
          })
        }
      })
    }
```

createTranslation():
```
...mapActions('u-translations', {
      findTranslation: 'find',
      createTranslation: 'create',
      patchTranslation: 'patch'
    }),
```

store:
```
service('u-translations', {
      idField: 'id' //What to set this to?
    }),
```

Just like #61, the data is added to the database , and the returned promise throws the same error.

However, it does not appear that my data is sent as an array, like in the above mentioned issue. The problem is probably because of the composite primary key. I have tried setting the `idField` in the store to different combinations, but the ones I have tried does not seem to help.

Any idea what might cause this, and how I can solve it?

Regards,

**Comment by fionagithub** [comment]
+1

**Comment by Torge** [comment]
@bobcat1 you need some kind of unique id for the store. What does the 'createTranslation result' look like?

**Comment by bobcat1** [comment]
@Torge I have since changed the code structure and changed the primary key to a single field instead of a composite, so this is not a problem for me personally anymore.

However it does seem like it doesn't like composite primary keys, which is a shame.

**Comment by marshallswain** [comment]
I looked into what it would take to support compound ids, today.  It will be a fairly significant time investment.  I don't plan on putting myself in a situation where I require this, so I'm going to close this, for now.  I'm happy to reopen if somebody would like to champion this, or to even do it myself if somebody is working for a company that requires this feature and would like to hire me to do it.  It's just not worth the effort in the meantime.
