### ISSUE TITLE
persist auth module state

### ISSUE THREAD

**Issue by nueko** [feathers-plus/feathers-vuex#68]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.
- [ ] Tell us what broke. The more detailed the better.

### Expected behavior
The authentication persist as it stored in browser storage

### Actual behavior
the authentication ignore the token in storage

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
latest
**NodeJS version**:
8.9
**Operating System**:
Win10
**Browser Version**:
chrome 62
**React Native Version**:

**Module Loader**:

**Comment by rayfoss** [comment]
This may not be running on the browser, as is the case with nuxt. And it's fairly easy to make it reauthenticate, which does in fact use browser cookies by default. You could save the state using NeDB/localforage, but that's way way beyond the scope of this particular module.


Anyway, here's how I persist in a way that allows local offline mutation:
```
export default feathersClient = feathers() //connects to socks

export const feathersCache = feathers() // connects to NeDB/localforage browserside
  .configure(hooks())
```
You could switch it back and forward using an adapter module...

```let backend = feathersClient

export {backend as default}
export function goLive () {
  backend = feathersClient
}

export function goMock () {
  backend = feathersCache
}```
