### ISSUE TITLE
auth-module do not register custom getters

### ISSUE THREAD

**Issue by AlbertoRota** [feathers-plus/feathers-vuex#69]
### Steps to reproduce
Create a new Vuex store, registering the auth-module with a custom getter.
Call the custom getter.

```
const customGetters = {
  oneTwoThree (state) {
    return 123
  }
}
const store = new Vuex.Store({
  plugins: [
    auth({ getters: customGetters })
  ]
})

assert(store.getters['auth/oneTwoThree'] === 123, 'the custom getter was available')
```
(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [x] Tell us what broke. The more detailed the better.
- [x] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
The getter returns the correct value from the store

### Actual behavior
The getter is not registered

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by marshallswain** [comment]
I believe this is resolved in the referenced commits / PR.  Please reopen if I'm mistaken.
