### ISSUE TITLE
Release article

### ISSUE THREAD

**Issue by marshallswain** [feathers-plus/feathers-vuex#7]
This deserves a fancy release article after the Auk announcement.

**Comment by MVSICA-FICTA** [comment]
Just maybe Vuex can still be useful, really thinking about a RxJS based store, something along the lines of ngrx but not specific to any framework. Lord, lift me up on higher ground!

**Comment by daffl** [comment]
Wouldn't that just be https://github.com/feathersjs/feathers-reactive?

**Comment by MVSICA-FICTA** [comment]
Yes, it is starting to look like that, just looking at feathers-reactive now. It also seems like services can double as stores exposing Observables, backed by an in-memory database. If so, then would an extra layer of state objects be necessary? Could a functional reducer not just interact with the BehaviorSubject noted in issue #39?

Will keep learning and seeing how this integrates into a intent to task to reducer flow. Very impressed by Feathers, outstanding!

**Comment by marshallswain** [comment]
I'm pretty sure the answer is yes.  I'd love to see a solution that just runs on RxJS that **also** includes some dev tools for time travel, etc.  I've just reached a point that I don't want to build it myself.  I want to leverage other tools and build some cool apps with existing tools.  However, I'm happy to help if somebody else is the champion  :wink:

**Comment by MVSICA-FICTA** [comment]
Super to learn more about feathers-reactive, will simplify a ton of things for me. My objective (mission) is to see my project through, so I do a lot of digging to make it so. In that right I do feel like a true champion leading a cause that many should enjoy, once released. Will keep factoring and keep in touch 🚀

**Comment by MVSICA-FICTA** [comment]
Still looking forward to the "fancy release article" :) 

Some further thoughts about the ultimate Vuex here: 

https://github.com/vuejs/vuex-observable/issues/2#issuecomment-301721923

**Comment by marshallswain** [comment]
The release article will happen once 1.0 is out and working with Nuxt.

**Comment by marshallswain** [comment]
Version 1.x has shipped!  `npm install feathers-vuex@latest`

Time for a release article!

**Comment by marshallswain** [comment]
This is my favorite issue!  I'm about to ship 2.x.  I swear I'll get to this.  :)

**Comment by marshallswain** [comment]
Ah hell.  I give up.  lol
