### ISSUE TITLE
[feature] remove action API, with params

### ISSUE THREAD

**Issue by rayfoss** [feathers-plus/feathers-vuex#71]
### Expected behavior
feathers-vuex action API should be `remove([id, params])`, as the one for the update action is `update([id, data, params])` and the feathers service method is `remove(id, params)`

This prevents passing parameters to remove, disabling softDelete or doing multi-record query deletes.

### Actual behavior
The current API is `remove(id)`. parameters are not supported.

### Workaround
Use the feathers service method directly. 

I'm not sure if this handles soft delete or any sort of complicated remove hook. I assume the record is removed from the store by the id given on the removed service event.

**Comment by marshallswain** [comment]
Development for this is complete.  This will be available once the `models` branch has been merged.
