### ISSUE TITLE
How to unsubscribe?

### ISSUE THREAD

**Issue by jakobrosenberg** [feathers-plus/feathers-vuex#74]
I'm loving this package, but one thing puzzles me. ``store.dispatch('things/find')`` keeps my data reactive, so how do I unsubscribe?

**Comment by jakobrosenberg** [comment]
Thanks MaximeLong. Would that stop the server from broadcasting or stop the client from listening?

**Comment by marshallswain** [comment]
@jakobrosenberg that only stops the client from listening.  On the server, you'd use either event filtering or event channels (new in Buzzard) to stop the messages.
