### ISSUE TITLE
NuxtServerError: You must provide a Feathers Client instance to feathers-vuex

### ISSUE THREAD

**Issue by ruslankonev** [feathers-plus/feathers-vuex#76]
Test using feathers-vuex in feathers-nuxt, feathers-vuex in first parameter expect a Feathers Client instance, not vuex store. How it can work properly? 
![image](https://user-images.githubusercontent.com/2588730/34199445-e2287596-e57e-11e7-90c7-be94aab00559.png)

**Comment by amizzo87** [comment]
Did you ever resolve this?

**Comment by marshallswain** [comment]
@ruslankonev `feathers-vuex` has to be initialized as shown in the examples in the readme: https://github.com/feathers-plus/feathers-vuex#use
