### ISSUE TITLE
Reactive auth user object

### ISSUE THREAD

**Issue by XXiphias** [feathers-plus/feathers-vuex#77]
When you authenticate via feathers you can have it return a user object with the authenticated user. Currently that user object is not reactive like everything else from feathers services. It does not update automatically if there are changes on the server. This small fix will make it reactive. marshall suggested posting it here to make it easier to add to the code base in the future. (He also came up with the original psuedo-code so thanks for that! ;))

```
function updateAuthUser(updatedUser) {
  const currentUser = store.state.auth.user;
  if (currentUser && (currentUser._id === updatedUser._id)) {
    store.commit('auth/setUser', updatedUser);
  }
}

feathersClient.service('users').on('patched', (user) => {
  updateAuthUser(user);
});
feathersClient.service('users').on('updated', (user) => {
  updateAuthUser(user);
});
```

I personally have this code in main.js and am importing the feathersClient. If you place it elsewhere you may need to make some modifications to the code so that it will work with your store object.

**Comment by gustojs** [comment]
```
If you place it elsewhere you may need to make some modifications to the code
```
I've been thinking of keeping it in a custom action of auth module. Sadly only default actions get feathersClient as dependency, not the custom ones, so I failed to use feathersClient.

**Comment by gustojs** [comment]
I'm using it now as custom action in auth module:
```
const customActions = function (feathersClient) {
  return {
    watchUser ({ state, dispatch }) {
      feathersClient.service('users').on('patched', (user) => {
        if (state.user && state.user._id === user._id) {
          dispatch('populateUser', user._id)
        }
      })
    }
  }
}

export const plugins = [
  auth({
    actions: customActions(feathersClient)
  })
]
```
This could be potentially implemented as default action.

**Comment by rayfoss** [comment]
I'm not sure what the issue is. feathers-vuex already makes a get call to your user service. If your user changes on the server it will also update `auth.user`. The only hiccup I'm having is that Vue doesn't see the change in `auth.user` so my components don't react.

The latter is a proper vue reactive property, meaning components react with any change to it.
```
    ...mapState('auth', {
      user: 'user'
    }),
    ...mapState('user', {
      usir: 'keyedById' // using as keyedById.myUserId
    }),
```

**Comment by marshallswain** [comment]
In the latest pre-release, version `1.2.0-pre.21`, the user object store in the `auth` state is now a reference to the user object in the `users` service.  Please upgrade to the pre-release.

`npm i feathers-vuex@pre --save`

https://github.com/feathers-plus/feathers-vuex/blob/models/notes.md#reactive-user-data-in-auth-store
