### ISSUE TITLE
Won't connect to feathersjs services

### ISSUE THREAD

**Issue by amizzo87** [feathers-plus/feathers-vuex#80]
Apologies for the noob question, but I'm just getting started out with Nuxt/feathers-vuex and am having issues. I'm sure I'm missing something very basic, but feathers-vuex doesn't seem to be "connecting" to the feathers services I've defined.

Here's store/index.js:
````import Vue from 'vue'
import Vuex from 'vuex'
import feathersVuex from 'feathers-vuex'
import feathersClient from '../feathers-client'

const { service } = feathersVuex(feathersClient, { idField: 'id' })

Vue.use(Vuex)
 
const createStore = () => { 
    
    return new Vuex.Store({
     plugins: [ 
            service('api/users')
    ]
    })
}

  
  export default createStore;
````
And here's feathers-client.js:
````
import feathers from '@feathersjs/client'
import restClient from '@feathersjs/rest-client'
import feathersVuex from 'feathers-vuex'
import axios from '~axios'

const feathersClient = feathers()
     .configure(restClient('http://localhost:3030').axios(axios));

export default feathersClient
````

I have a feathers api endpoint at `/api/users`, but no matter what variant of 'users' or 'api/users' etc i put in `service()`, nothing seems to be rendering in the vue template:

````
<template>
  <section class="container">
    <ul>
          <li v-for="user in users" :key="user.email">{{user.id}}</li>
    </ul>
  </section>
</template>

<script>
import { mapGetters, mapState } from 'vuex'

export default { 
    name: 'test',
    computed: mapState([
        'users'
    ])
}

</script>
````

This shows nothing, despite `users` having records populated populated in the SQL database.

Any ideas would be more than welcome! I'm sure I'm missing something, I'm just not sure what...

**Comment by Mattchewone** [comment]
In your first snippet you are using:
```
Vue.use(Vuex)
```
But you haven't imported `Vue`.

I can't see anything obvious but I haven't used nuxt yet. Are you able to put a sample repo together so I could clone and reproduce locally?

**Comment by amizzo87** [comment]
@Mattchewone Hmm must've been a copy-paste mistake on my part; I do import Vue. I've put a sample repo together [here ](https://github.com/amizzo87/feathers-vuex-nuxt)- using KnexJs with SQL Server on my end but you should be able to reproduce using KnexJs with any locally running db. Let me know what you think and thanks for the help!

**Comment by marshallswain** [comment]
@amizzo87 I don't see any actions being used.  Actions used for server communication.  Getters are used for local interaction with the store.

```js
import { mapActions } from 'vuex'

export default {
  methods: {
    ...mapActions('users', { fetchUsers: 'find' })
  },
  created () {
    this.fetchUsers()
  }
}
```

I'm going to close this.  Feel free to reopen if you find an issue.
