### ISSUE TITLE
unnecessary console.log "no cookies found"

### ISSUE THREAD

**Issue by supermomme** [feathers-plus/feathers-vuex#84]
### Steps to reproduce
Using "initAuth" with no cookie set.

### Expected behavior
It shouldn't log to the console. It already returns undefined and works as expected, no need to flood the log.

### Actual behavior
It logs to the console [at this line](https://github.com/feathers-plus/feathers-vuex/blob/1bfab9763cb69302d0d3ad8fa5dc053565a17045/src/utils.js#L78).

**Comment by marshallswain** [comment]
Closed by #96 
Thanks!
