### ISSUE TITLE
dispatch('craeate', ...) returning object with _id=null

### ISSUE THREAD

**Issue by daenuprobst** [feathers-plus/feathers-vuex#85]
### Steps to reproduce
When dispatching `model/create`, the result has an `_id` of `null`.

Example:
```javascript
this.$store.dispatch('someModel/create', { ... }).then(result => {
    // result._id is null
})
```

### Expected behavior
The `_id` should be populated with the id value.

### Actual behavior
The `_id` is not populated, it is `null`

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
"@feathersjs/client": "^3.3.1"
"@feathersjs/feathers": "^3.1.0"
"feathers-vuex": "^1.1.4",

"@feathersjs/feathers": "^3.1.2",
"feathers-mongoose": "^6.1.0",

**NodeJS version**:
v8.9.4

**Comment by marshallswain** [comment]
Can you post some information on how to reproduce this?  I'm going to close this until then.
