### ISSUE TITLE
Clarification on Reactive or not

### ISSUE THREAD

**Issue by samburgers** [feathers-plus/feathers-vuex#86]
Hi, 

Getting my head around the readme, and noticed these two sort of conflicting statements. Just wondering if someone could possibly show some basic vue template style example of a reactive list with vuex.

Thanks!

```
Note: as of version 1.0.0 feathers-reactive is no longer required to get socket updates.
```

```
Note: The find action no longer returns reactive lists. The list data will still be reactive, but new matches that arrive from the server do NOT get automatically added to lists. There are two solutions to this:

Use the find action to pull in data from the server. Use the find getter to pull a reactive list from the store.
Configure the feathers-reactive plugin with RxJS on your Feathers Client instance. Read the docs for implementation details.
```

**Comment by maximeLong** [comment]
Did you end up finding an example of how to make lists reactive?

**Comment by samburgers** [comment]
Yes i did, there is some sample code here. (if that still isn't reactive, also check your websocket channel settings in your feathers server setup)

https://github.com/feathers-plus/feathers-vuex/issues/88

In summary `feathers-vuex` handles reactivity very well! and you don't need `feathers-reactive` or `RxJS`.
