### ISSUE TITLE
Hi,  feathers-vuex upgrade for @feathersjs v3 

### ISSUE THREAD

**Issue by oktayari** [feathers-plus/feathers-vuex#91]
hi,

when will be possible to get new release of feather-vuex for the  @feathersjs v3 
Thanks

**Comment by marshallswain** [comment]
No update is needed.  It just works once you've updated your packages to the "v3" versions.  I've updated the readme example.  https://github.com/feathers-plus/feathers-vuex/blob/master/README.md#use
