### ISSUE TITLE
What nearly made me not to use feather-vuex

### ISSUE THREAD

**Issue by litti** [feathers-plus/feathers-vuex#99]
In readme.md it says feather-vuex is not compatible with version 0.5x of feathers-reactive https://github.com/feathers-plus/feathers-vuex#important. But later it says feathers-reactive isn't needed anymore starting with feathers-vuex 1.0. Maybe it would be helpful to make this important hint for long time users not as prominent as it is or add some text that it is only for long time users? This hint nearly made me not to use feathers-vuex because who wants to use a module which is not up to date ;-)

**Comment by marshallswain** [comment]
Thanks for this update.  I actually just noticed this tonight, too, while reading it again.  I'll update this.
